// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1179_40 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln1179,
        select_ln1179,
        parkingSpotsRemainingAtCurrentIndexXC_data_address0,
        parkingSpotsRemainingAtCurrentIndexXC_data_ce0,
        parkingSpotsRemainingAtCurrentIndexXC_data_q0,
        tempParkingH_address0,
        tempParkingH_ce0,
        tempParkingH_we0,
        tempParkingH_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] zext_ln1179;
input  [16:0] select_ln1179;
output  [7:0] parkingSpotsRemainingAtCurrentIndexXC_data_address0;
output   parkingSpotsRemainingAtCurrentIndexXC_data_ce0;
input  [63:0] parkingSpotsRemainingAtCurrentIndexXC_data_q0;
output  [7:0] tempParkingH_address0;
output   tempParkingH_ce0;
output   tempParkingH_we0;
output  [63:0] tempParkingH_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1179_fu_114_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] writeIdx_3_reg_168;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1179_2_fu_145_p1;
reg   [8:0] writeIdx_fu_46;
wire   [8:0] writeIdx_4_fu_119_p2;
wire    ap_loop_init;
reg   [63:0] readIdx_fu_50;
wire   [63:0] readIdx_4_fu_129_p2;
wire   [63:0] zext_ln1179_cast_fu_93_p1;
reg    parkingSpotsRemainingAtCurrentIndexXC_data_ce0_local;
reg    tempParkingH_we0_local;
reg    tempParkingH_ce0_local;
wire   [16:0] zext_ln1179_1_fu_110_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 writeIdx_fu_46 = 9'd0;
#0 readIdx_fu_50 = 64'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            readIdx_fu_50 <= zext_ln1179_cast_fu_93_p1;
        end else if (((icmp_ln1179_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            readIdx_fu_50 <= readIdx_4_fu_129_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            writeIdx_fu_46 <= 9'd0;
        end else if (((icmp_ln1179_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            writeIdx_fu_46 <= writeIdx_4_fu_119_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        writeIdx_3_reg_168 <= writeIdx_fu_46;
    end
end

always @ (*) begin
    if (((icmp_ln1179_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        parkingSpotsRemainingAtCurrentIndexXC_data_ce0_local = 1'b1;
    end else begin
        parkingSpotsRemainingAtCurrentIndexXC_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tempParkingH_ce0_local = 1'b1;
    end else begin
        tempParkingH_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tempParkingH_we0_local = 1'b1;
    end else begin
        tempParkingH_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln1179_fu_114_p2 = ((zext_ln1179_1_fu_110_p1 == select_ln1179) ? 1'b1 : 1'b0);

assign parkingSpotsRemainingAtCurrentIndexXC_data_address0 = readIdx_fu_50;

assign parkingSpotsRemainingAtCurrentIndexXC_data_ce0 = parkingSpotsRemainingAtCurrentIndexXC_data_ce0_local;

assign readIdx_4_fu_129_p2 = (readIdx_fu_50 + 64'd1);

assign tempParkingH_address0 = zext_ln1179_2_fu_145_p1;

assign tempParkingH_ce0 = tempParkingH_ce0_local;

assign tempParkingH_d0 = parkingSpotsRemainingAtCurrentIndexXC_data_q0;

assign tempParkingH_we0 = tempParkingH_we0_local;

assign writeIdx_4_fu_119_p2 = (writeIdx_fu_46 + 9'd1);

assign zext_ln1179_1_fu_110_p1 = writeIdx_fu_46;

assign zext_ln1179_2_fu_145_p1 = writeIdx_3_reg_168;

assign zext_ln1179_cast_fu_93_p1 = zext_ln1179;

endmodule //atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1179_40
