// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_push_back (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        moveStream_TDATA,
        moveStream_TVALID,
        moveStream_TREADY,
        this_count_read,
        move_address0,
        move_ce0,
        move_q0,
        move_address1,
        move_ce1,
        move_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [511:0] moveStream_TDATA;
output   moveStream_TVALID;
input   moveStream_TREADY;
input  [31:0] this_count_read;
output  [9:0] move_address0;
output   move_ce0;
input  [15:0] move_q0;
output  [9:0] move_address1;
output   move_ce1;
input  [15:0] move_q1;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[511:0] moveStream_TDATA;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_idle;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_ready;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TREADY;
wire   [9:0] grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address0;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce0;
wire   [9:0] grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address1;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce1;
wire   [511:0] grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TDATA;
wire    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TVALID;
reg    grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [511:0] moveStream_TDATA_reg;
wire   [31:0] add_ln613_fu_40_p2;
reg   [31:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

atomflow_controller_push_back_Pipeline_VITIS_LOOP_601_1 grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start),
    .ap_done(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done),
    .ap_idle(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_idle),
    .ap_ready(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_ready),
    .moveStream_TREADY(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TREADY),
    .move_address0(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address0),
    .move_ce0(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce0),
    .move_q0(move_q0),
    .move_address1(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address1),
    .move_ce1(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce1),
    .move_q1(move_q1),
    .moveStream_TDATA(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TDATA),
    .moveStream_TVALID(grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TVALID)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_preg <= add_ln613_fu_40_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_ready == 1'b1)) begin
            grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        moveStream_TDATA_reg <= grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TDATA;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return = add_ln613_fu_40_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        moveStream_TDATA = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TDATA;
    end else begin
        moveStream_TDATA = moveStream_TDATA_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln613_fu_40_p2 = (this_count_read + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_ap_start_reg;

assign grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TREADY = (moveStream_TREADY & ap_CS_fsm_state2);

assign moveStream_TVALID = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_moveStream_TVALID;

assign move_address0 = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address0;

assign move_address1 = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_address1;

assign move_ce0 = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce0;

assign move_ce1 = grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32_move_ce1;

endmodule //atomflow_controller_push_back
