
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [2:0] axis_block_sigs;
wire [16:0] inst_idle_sigs;
wire [5:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_clearFirstNRowsOrCols_HLSMoveStream_s_fu_288.grp_push_back_fu_2114.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.moveStream_TDATA_blk_n;
assign axis_block_sigs[1] = ~grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_sortRemainingRowsOrCols_HLSMoveStream_s_fu_299.grp_push_back_fu_18715.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.moveStream_TDATA_blk_n;
assign axis_block_sigs[2] = ~grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_resolveSortingDeficiencies_HLSMoveStream_s_fu_342.grp_push_back_fu_3960.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.moveStream_TDATA_blk_n;

assign inst_idle_sigs[0] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.ap_idle;
assign inst_block_sigs[0] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.ap_continue);
assign inst_idle_sigs[1] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_1_U0.ap_idle;
assign inst_block_sigs[1] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_1_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_1_U0.ap_continue);
assign inst_idle_sigs[2] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.getLocalImages_single_U0.ap_idle;
assign inst_block_sigs[2] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.getLocalImages_single_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.getLocalImages_single_U0.ap_continue);
assign inst_idle_sigs[3] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.Image_extract_next_U0.ap_idle;
assign inst_block_sigs[3] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.Image_extract_next_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.Image_extract_next_U0.ap_continue);
assign inst_idle_sigs[4] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.matrix_sum_prod_U0.ap_idle;
assign inst_block_sigs[4] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.matrix_sum_prod_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.matrix_sum_prod_U0.ap_continue);
assign inst_idle_sigs[5] = grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_U0.ap_idle;
assign inst_block_sigs[5] = (grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_U0.ap_done & ~grp_reconstruct_fu_404.dataflow_in_loop_VITIS_LOOP_241_1_1_U0.dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_U0.ap_continue);

assign inst_idle_sigs[6] = 1'b0;
assign inst_idle_sigs[7] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.ap_idle;
assign inst_idle_sigs[8] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_clearFirstNRowsOrCols_HLSMoveStream_s_fu_288.ap_idle;
assign inst_idle_sigs[9] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_clearFirstNRowsOrCols_HLSMoveStream_s_fu_288.grp_push_back_fu_2114.ap_idle;
assign inst_idle_sigs[10] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_clearFirstNRowsOrCols_HLSMoveStream_s_fu_288.grp_push_back_fu_2114.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.ap_idle;
assign inst_idle_sigs[11] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_sortRemainingRowsOrCols_HLSMoveStream_s_fu_299.ap_idle;
assign inst_idle_sigs[12] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_sortRemainingRowsOrCols_HLSMoveStream_s_fu_299.grp_push_back_fu_18715.ap_idle;
assign inst_idle_sigs[13] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_sortRemainingRowsOrCols_HLSMoveStream_s_fu_299.grp_push_back_fu_18715.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.ap_idle;
assign inst_idle_sigs[14] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_resolveSortingDeficiencies_HLSMoveStream_s_fu_342.ap_idle;
assign inst_idle_sigs[15] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_resolveSortingDeficiencies_HLSMoveStream_s_fu_342.grp_push_back_fu_3960.ap_idle;
assign inst_idle_sigs[16] = grp_sortArray_impl_state_accessor_HLSMoveStream_s_fu_487.grp_resolveSortingDeficiencies_HLSMoveStream_s_fu_342.grp_push_back_fu_3960.grp_push_back_Pipeline_VITIS_LOOP_601_1_fu_32.ap_idle;

atomflow_controller_hls_deadlock_idx0_monitor atomflow_controller_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
