-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_609_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    unusableWriteIdx : IN STD_LOGIC_VECTOR (15 downto 0);
    currentSize : IN STD_LOGIC_VECTOR (15 downto 0);
    backIdx : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln620_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    unusableInfo_usableAtoms_data_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    unusableInfo_usableAtoms_data_ce0 : OUT STD_LOGIC;
    unusableInfo_usableAtoms_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    unusableInfo_usableAtoms_data_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    unusableInfo_usableAtoms_data_ce1 : OUT STD_LOGIC;
    unusableInfo_usableAtoms_data_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv7 : IN STD_LOGIC_VECTOR (31 downto 0);
    unusableAtoms_data_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    unusableAtoms_data_ce1 : OUT STD_LOGIC;
    unusableAtoms_data_we1 : OUT STD_LOGIC;
    unusableAtoms_data_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    threshold : IN STD_LOGIC_VECTOR (15 downto 0);
    unusableWriteIdx_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    unusableWriteIdx_1_out_ap_vld : OUT STD_LOGIC;
    frontIdx_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    frontIdx_out_ap_vld : OUT STD_LOGIC;
    backIdx_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    backIdx_1_out_ap_vld : OUT STD_LOGIC;
    discardCount_01099_i_ce_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    discardCount_01099_i_ce_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_609_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_ln615_1_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln609_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal discardCount_01099_i_ce_reg_211 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal backIdx_3_reg_469 : STD_LOGIC_VECTOR (15 downto 0);
    signal frontIdx_2_reg_474 : STD_LOGIC_VECTOR (15 downto 0);
    signal unusableAtoms_data_addr_reg_483 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln630_fu_283_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln620_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln621_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal currentSize_1_fu_84 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal currentSize_4_fu_359_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal unusableWriteIdx_1_fu_88 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal unusableWriteIdx_4_fu_353_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal backIdx_1_fu_92 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal backIdx_4_fu_397_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln623_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_backIdx_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal frontIdx_fu_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal frontIdx_3_fu_407_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_frontIdx_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal discardCount_1_fu_100 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal discardCount_3_fu_272_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal unusableInfo_usableAtoms_data_ce1_local : STD_LOGIC;
    signal unusableInfo_usableAtoms_data_ce0_local : STD_LOGIC;
    signal unusableAtoms_data_we1_local : STD_LOGIC;
    signal unusableAtoms_data_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal unusableAtoms_data_ce1_local : STD_LOGIC;
    signal add_ln630_fu_278_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln615_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_305_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln617_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln618_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln615_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln615_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln620_fu_333_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln621_fu_343_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln623_fu_380_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln623_fu_385_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_325 : BOOLEAN;
    signal ap_condition_104 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component atomflow_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component atomflow_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    backIdx_1_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    backIdx_1_fu_92 <= backIdx;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_0))) then 
                    backIdx_1_fu_92 <= backIdx_4_fu_397_p2;
                end if;
            end if; 
        end if;
    end process;

    currentSize_1_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    currentSize_1_fu_84 <= currentSize;
                elsif ((ap_const_boolean_1 = ap_condition_325)) then 
                    currentSize_1_fu_84 <= currentSize_4_fu_359_p2;
                end if;
            end if; 
        end if;
    end process;

    discardCount_01099_i_ce_reg_211_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_104)) then
                if ((icmp_ln609_fu_266_p2 = ap_const_lv1_1)) then 
                    discardCount_01099_i_ce_reg_211 <= ap_const_lv9_100;
                elsif (((icmp_ln609_fu_266_p2 = ap_const_lv1_0) and (or_ln615_1_fu_327_p2 = ap_const_lv1_1))) then 
                    discardCount_01099_i_ce_reg_211 <= discardCount_1_fu_100;
                end if;
            end if; 
        end if;
    end process;

    discardCount_1_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    discardCount_1_fu_100 <= ap_const_lv9_0;
                elsif ((ap_const_boolean_1 = ap_condition_325)) then 
                    discardCount_1_fu_100 <= discardCount_3_fu_272_p2;
                end if;
            end if; 
        end if;
    end process;

    frontIdx_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    frontIdx_fu_96 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_1))) then 
                    frontIdx_fu_96 <= frontIdx_3_fu_407_p2;
                end if;
            end if; 
        end if;
    end process;

    unusableWriteIdx_1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    unusableWriteIdx_1_fu_88 <= unusableWriteIdx;
                elsif ((ap_const_boolean_1 = ap_condition_325)) then 
                    unusableWriteIdx_1_fu_88 <= unusableWriteIdx_4_fu_353_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                backIdx_3_reg_469 <= ap_sig_allocacmp_backIdx_3;
                frontIdx_2_reg_474 <= ap_sig_allocacmp_frontIdx_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                unusableAtoms_data_addr_reg_483 <= zext_ln630_fu_283_p1(16 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln620_fu_333_p2 <= std_logic_vector(unsigned(zext_ln620_1) + unsigned(ap_sig_allocacmp_frontIdx_2));
    add_ln621_fu_343_p2 <= std_logic_vector(unsigned(zext_ln620_1) + unsigned(ap_sig_allocacmp_backIdx_3));
    add_ln623_fu_380_p2 <= std_logic_vector(unsigned(conv7) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln630_fu_278_p2 <= std_logic_vector(unsigned(zext_ln620_1) + unsigned(unusableWriteIdx_1_fu_88));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_104_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_104 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_325_assign_proc : process(ap_enable_reg_pp0_iter1, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2)
    begin
                ap_condition_325 <= ((icmp_ln609_fu_266_p2 = ap_const_lv1_0) and (or_ln615_1_fu_327_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln609_fu_266_p2 = ap_const_lv1_1) or (or_ln615_1_fu_327_p2 = ap_const_lv1_1)))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_backIdx_3_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, backIdx_1_fu_92, backIdx_4_fu_397_p2, icmp_ln623_fu_391_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_0))) then 
            ap_sig_allocacmp_backIdx_3 <= backIdx_4_fu_397_p2;
        else 
            ap_sig_allocacmp_backIdx_3 <= backIdx_1_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_frontIdx_2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln623_fu_391_p2, frontIdx_fu_96, frontIdx_3_fu_407_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_frontIdx_2 <= frontIdx_3_fu_407_p2;
        else 
            ap_sig_allocacmp_frontIdx_2 <= frontIdx_fu_96;
        end if; 
    end process;

    backIdx_1_out <= backIdx_1_fu_92;

    backIdx_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln609_fu_266_p2 = ap_const_lv1_1) or (or_ln615_1_fu_327_p2 = ap_const_lv1_1)))) then 
            backIdx_1_out_ap_vld <= ap_const_logic_1;
        else 
            backIdx_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    backIdx_4_fu_397_p2 <= std_logic_vector(unsigned(backIdx_3_reg_469) + unsigned(ap_const_lv16_FFFF));
    currentSize_4_fu_359_p2 <= std_logic_vector(unsigned(currentSize_1_fu_84) + unsigned(ap_const_lv16_FFFF));
    discardCount_01099_i_ce_out <= discardCount_01099_i_ce_reg_211;

    discardCount_01099_i_ce_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln609_fu_266_p2 = ap_const_lv1_1) or (or_ln615_1_fu_327_p2 = ap_const_lv1_1)))) then 
            discardCount_01099_i_ce_out_ap_vld <= ap_const_logic_1;
        else 
            discardCount_01099_i_ce_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    discardCount_3_fu_272_p2 <= std_logic_vector(unsigned(discardCount_1_fu_100) + unsigned(ap_const_lv9_1));
    frontIdx_3_fu_407_p2 <= std_logic_vector(unsigned(frontIdx_2_reg_474) + unsigned(ap_const_lv16_1));
    frontIdx_out <= frontIdx_fu_96;

    frontIdx_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln609_fu_266_p2 = ap_const_lv1_1) or (or_ln615_1_fu_327_p2 = ap_const_lv1_1)))) then 
            frontIdx_out_ap_vld <= ap_const_logic_1;
        else 
            frontIdx_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln609_fu_266_p2 <= "1" when (discardCount_1_fu_100 = ap_const_lv9_100) else "0";
    icmp_ln615_fu_288_p2 <= "1" when (unsigned(threshold) < unsigned(currentSize_1_fu_84)) else "0";
    icmp_ln617_fu_299_p2 <= "1" when (unsigned(ap_sig_allocacmp_frontIdx_2) > unsigned(ap_sig_allocacmp_backIdx_3)) else "0";
    icmp_ln618_fu_315_p2 <= "0" when (tmp_fu_305_p4 = ap_const_lv8_0) else "1";
    icmp_ln623_fu_391_p2 <= "1" when (signed(unusableInfo_usableAtoms_data_q1) > signed(sub_ln623_fu_385_p2)) else "0";
    or_ln615_1_fu_327_p2 <= (xor_ln615_fu_293_p2 or or_ln615_fu_321_p2);
    or_ln615_fu_321_p2 <= (icmp_ln618_fu_315_p2 or icmp_ln617_fu_299_p2);
    sub_ln623_fu_385_p2 <= std_logic_vector(unsigned(add_ln623_fu_380_p2) - unsigned(unusableInfo_usableAtoms_data_q0));
    tmp_fu_305_p4 <= unusableWriteIdx_1_fu_88(15 downto 8);
    unusableAtoms_data_address1 <= unusableAtoms_data_addr_reg_483;
    unusableAtoms_data_ce1 <= unusableAtoms_data_ce1_local;

    unusableAtoms_data_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln623_fu_391_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_0)))) then 
            unusableAtoms_data_ce1_local <= ap_const_logic_1;
        else 
            unusableAtoms_data_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    unusableAtoms_data_d1 <= unusableAtoms_data_d1_local;

    unusableAtoms_data_d1_local_assign_proc : process(ap_enable_reg_pp0_iter2, unusableInfo_usableAtoms_data_q0, unusableInfo_usableAtoms_data_q1, ap_block_pp0_stage0, icmp_ln623_fu_391_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((icmp_ln623_fu_391_p2 = ap_const_lv1_1)) then 
                unusableAtoms_data_d1_local <= unusableInfo_usableAtoms_data_q1;
            elsif ((icmp_ln623_fu_391_p2 = ap_const_lv1_0)) then 
                unusableAtoms_data_d1_local <= unusableInfo_usableAtoms_data_q0;
            else 
                unusableAtoms_data_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            unusableAtoms_data_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    unusableAtoms_data_we1 <= unusableAtoms_data_we1_local;

    unusableAtoms_data_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln623_fu_391_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln623_fu_391_p2 = ap_const_lv1_0)))) then 
            unusableAtoms_data_we1_local <= ap_const_logic_1;
        else 
            unusableAtoms_data_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    unusableInfo_usableAtoms_data_address0 <= zext_ln621_fu_348_p1(16 - 1 downto 0);
    unusableInfo_usableAtoms_data_address1 <= zext_ln620_fu_338_p1(16 - 1 downto 0);
    unusableInfo_usableAtoms_data_ce0 <= unusableInfo_usableAtoms_data_ce0_local;

    unusableInfo_usableAtoms_data_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            unusableInfo_usableAtoms_data_ce0_local <= ap_const_logic_1;
        else 
            unusableInfo_usableAtoms_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    unusableInfo_usableAtoms_data_ce1 <= unusableInfo_usableAtoms_data_ce1_local;

    unusableInfo_usableAtoms_data_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            unusableInfo_usableAtoms_data_ce1_local <= ap_const_logic_1;
        else 
            unusableInfo_usableAtoms_data_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    unusableWriteIdx_1_out <= unusableWriteIdx_1_fu_88;

    unusableWriteIdx_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln615_1_fu_327_p2, icmp_ln609_fu_266_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln609_fu_266_p2 = ap_const_lv1_1) or (or_ln615_1_fu_327_p2 = ap_const_lv1_1)))) then 
            unusableWriteIdx_1_out_ap_vld <= ap_const_logic_1;
        else 
            unusableWriteIdx_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    unusableWriteIdx_4_fu_353_p2 <= std_logic_vector(unsigned(unusableWriteIdx_1_fu_88) + unsigned(ap_const_lv16_1));
    xor_ln615_fu_293_p2 <= (icmp_ln615_fu_288_p2 xor ap_const_lv1_1);
    zext_ln620_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln620_fu_333_p2),64));
    zext_ln621_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln621_fu_343_p2),64));
    zext_ln630_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln630_fu_278_p2),64));
end behav;
