-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_780_15 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    end_colSelectionCount_6_ph : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_103 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (15 downto 0);
    end_colSelection_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    end_colSelection_ce0 : OUT STD_LOGIC;
    end_colSelection_we0 : OUT STD_LOGIC;
    end_colSelection_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    end_colSelection_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    end_colSelection_ce1 : OUT STD_LOGIC;
    end_colSelection_we1 : OUT STD_LOGIC;
    end_colSelection_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    indicesHigherMiddle_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    end_colSelectionCount_1_lcssa_i_ph_ce_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    end_colSelectionCount_1_lcssa_i_ph_ce_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_780_15 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln780_1_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln780_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal end_colSelectionCount_1_lcssa_i_ph_ce_reg_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal end_colSelectionCount_4_fu_170_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln786_fu_177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln786_1_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_3_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal end_colSelectionCount_fu_68 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal end_colSelectionCount_5_fu_229_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal end_colSelection_we1_local : STD_LOGIC;
    signal add_ln786_fu_164_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal end_colSelection_ce1_local : STD_LOGIC;
    signal end_colSelection_we0_local : STD_LOGIC;
    signal add_ln786_2_fu_223_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal end_colSelection_ce0_local : STD_LOGIC;
    signal trunc_ln786_fu_160_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_182_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_2_fu_192_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_205_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln5_fu_215_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_82 : BOOLEAN;
    signal ap_condition_231 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component atomflow_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component atomflow_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    end_colSelectionCount_1_lcssa_i_ph_ce_reg_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_82)) then
                if (((icmp_ln780_fu_155_p2 = ap_const_lv1_0) and (icmp_ln780_1_fu_200_p2 = ap_const_lv1_0))) then 
                    end_colSelectionCount_1_lcssa_i_ph_ce_reg_128 <= end_colSelectionCount_4_fu_170_p2;
                elsif ((icmp_ln780_fu_155_p2 = ap_const_lv1_1)) then 
                    end_colSelectionCount_1_lcssa_i_ph_ce_reg_128 <= end_colSelectionCount_fu_68;
                end if;
            end if; 
        end if;
    end process;

    end_colSelectionCount_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    end_colSelectionCount_fu_68 <= end_colSelectionCount_6_ph;
                elsif ((ap_const_boolean_1 = ap_condition_231)) then 
                    end_colSelectionCount_fu_68 <= end_colSelectionCount_5_fu_229_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_231)) then 
                    i_fu_64 <= i_3_fu_240_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln786_2_fu_223_p2 <= std_logic_vector(unsigned(or_ln5_fu_215_p3) + unsigned(empty));
    add_ln786_fu_164_p2 <= std_logic_vector(unsigned(trunc_ln786_fu_160_p1) + unsigned(empty));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_231_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln780_1_fu_200_p2, icmp_ln780_fu_155_p2)
    begin
                ap_condition_231 <= ((icmp_ln780_fu_155_p2 = ap_const_lv1_0) and (icmp_ln780_1_fu_200_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_82_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_82 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln780_1_fu_200_p2, icmp_ln780_fu_155_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln780_fu_155_p2 = ap_const_lv1_1) or (icmp_ln780_1_fu_200_p2 = ap_const_lv1_0)))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelectionCount_1_lcssa_i_ph_ce_out <= end_colSelectionCount_1_lcssa_i_ph_ce_reg_128;

    end_colSelectionCount_1_lcssa_i_ph_ce_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln780_1_fu_200_p2, icmp_ln780_fu_155_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((icmp_ln780_fu_155_p2 = ap_const_lv1_1) or (icmp_ln780_1_fu_200_p2 = ap_const_lv1_0)))) then 
            end_colSelectionCount_1_lcssa_i_ph_ce_out_ap_vld <= ap_const_logic_1;
        else 
            end_colSelectionCount_1_lcssa_i_ph_ce_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelectionCount_4_fu_170_p2 <= std_logic_vector(unsigned(end_colSelectionCount_fu_68) + unsigned(ap_const_lv8_1));
    end_colSelectionCount_5_fu_229_p2 <= std_logic_vector(unsigned(end_colSelectionCount_fu_68) + unsigned(ap_const_lv8_2));
    end_colSelection_address0 <= zext_ln786_1_fu_235_p1(4 - 1 downto 0);
    end_colSelection_address1 <= zext_ln786_fu_177_p1(4 - 1 downto 0);
    end_colSelection_ce0 <= end_colSelection_ce0_local;

    end_colSelection_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            end_colSelection_ce0_local <= ap_const_logic_1;
        else 
            end_colSelection_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelection_ce1 <= end_colSelection_ce1_local;

    end_colSelection_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            end_colSelection_ce1_local <= ap_const_logic_1;
        else 
            end_colSelection_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelection_d0 <= add_ln786_2_fu_223_p2;
    end_colSelection_d1 <= add_ln786_fu_164_p2;
    end_colSelection_we0 <= end_colSelection_we0_local;

    end_colSelection_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln780_1_fu_200_p2, icmp_ln780_fu_155_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln780_fu_155_p2 = ap_const_lv1_0) and (icmp_ln780_1_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            end_colSelection_we0_local <= ap_const_logic_1;
        else 
            end_colSelection_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelection_we1 <= end_colSelection_we1_local;

    end_colSelection_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln780_fu_155_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln780_fu_155_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            end_colSelection_we1_local <= ap_const_logic_1;
        else 
            end_colSelection_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_192_p3 <= (tmp_s_fu_182_p4 & ap_const_lv1_1);
    i_3_fu_240_p2 <= std_logic_vector(unsigned(i_fu_64) + unsigned(ap_const_lv32_2));
    icmp_ln780_1_fu_200_p2 <= "1" when (signed(i_2_fu_192_p3) < signed(indicesHigherMiddle_reload)) else "0";
    icmp_ln780_fu_155_p2 <= "1" when (i_fu_64 = empty_103) else "0";
    or_ln5_fu_215_p3 <= (tmp_2_fu_205_p4 & ap_const_lv1_1);
    tmp_2_fu_205_p4 <= i_fu_64(15 downto 1);
    tmp_s_fu_182_p4 <= i_fu_64(31 downto 1);
    trunc_ln786_fu_160_p1 <= i_fu_64(16 - 1 downto 0);
    zext_ln786_1_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(end_colSelectionCount_4_fu_170_p2),64));
    zext_ln786_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(end_colSelectionCount_fu_68),64));
end behav;
