// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_841_18 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        indexAC_idx2,
        indexAC_idx2_1,
        zext_ln620_1,
        unusableInfo_usableAtoms_data_address0,
        unusableInfo_usableAtoms_data_ce0,
        unusableInfo_usableAtoms_data_q0,
        start_colSelection_1_address0,
        start_colSelection_1_ce0,
        start_colSelection_1_we0,
        start_colSelection_1_d0,
        end_colSelection_1_address0,
        end_colSelection_1_ce0,
        end_colSelection_1_we0,
        end_colSelection_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] indexAC_idx2;
input  [16:0] indexAC_idx2_1;
input  [15:0] zext_ln620_1;
output  [15:0] unusableInfo_usableAtoms_data_address0;
output   unusableInfo_usableAtoms_data_ce0;
input  [31:0] unusableInfo_usableAtoms_data_q0;
output  [3:0] start_colSelection_1_address0;
output   start_colSelection_1_ce0;
output   start_colSelection_1_we0;
output  [15:0] start_colSelection_1_d0;
output  [3:0] end_colSelection_1_address0;
output   end_colSelection_1_ce0;
output   end_colSelection_1_we0;
output  [15:0] end_colSelection_1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln841_fu_137_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] start_colSelectionCount_reg_205;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln147_fu_159_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln848_fu_186_p1;
reg   [16:0] indexAC_idx2_2_fu_52;
wire   [16:0] indexAC_idx2_cast_fu_117_p1;
wire   [16:0] indexAC_idx2_5_fu_164_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_indexAC_idx2_4;
reg   [4:0] end_colSelectionCount_fu_56;
wire   [4:0] start_colSelectionCount_1_fu_143_p2;
reg   [4:0] ap_sig_allocacmp_start_colSelectionCount;
reg    unusableInfo_usableAtoms_data_ce0_local;
reg    start_colSelection_1_we0_local;
wire   [15:0] trunc_ln848_fu_180_p1;
reg    start_colSelection_1_ce0_local;
reg    end_colSelection_1_we0_local;
reg    end_colSelection_1_ce0_local;
wire   [15:0] trunc_ln147_fu_149_p1;
wire   [15:0] add_ln147_fu_153_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indexAC_idx2_2_fu_52 = 17'd0;
#0 end_colSelectionCount_fu_56 = 5'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln841_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            end_colSelectionCount_fu_56 <= start_colSelectionCount_1_fu_143_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            end_colSelectionCount_fu_56 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln841_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indexAC_idx2_2_fu_52 <= indexAC_idx2_5_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indexAC_idx2_2_fu_52 <= indexAC_idx2_cast_fu_117_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        start_colSelectionCount_reg_205 <= ap_sig_allocacmp_start_colSelectionCount;
    end
end

always @ (*) begin
    if (((icmp_ln841_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indexAC_idx2_4 = indexAC_idx2_cast_fu_117_p1;
    end else begin
        ap_sig_allocacmp_indexAC_idx2_4 = indexAC_idx2_2_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_start_colSelectionCount = 5'd0;
    end else begin
        ap_sig_allocacmp_start_colSelectionCount = end_colSelectionCount_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        end_colSelection_1_ce0_local = 1'b1;
    end else begin
        end_colSelection_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        end_colSelection_1_we0_local = 1'b1;
    end else begin
        end_colSelection_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        start_colSelection_1_ce0_local = 1'b1;
    end else begin
        start_colSelection_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        start_colSelection_1_we0_local = 1'b1;
    end else begin
        start_colSelection_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unusableInfo_usableAtoms_data_ce0_local = 1'b1;
    end else begin
        unusableInfo_usableAtoms_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln147_fu_153_p2 = (zext_ln620_1 + trunc_ln147_fu_149_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign end_colSelection_1_address0 = zext_ln848_fu_186_p1;

assign end_colSelection_1_ce0 = end_colSelection_1_ce0_local;

assign end_colSelection_1_d0 = trunc_ln848_fu_180_p1;

assign end_colSelection_1_we0 = end_colSelection_1_we0_local;

assign icmp_ln841_fu_137_p2 = ((ap_sig_allocacmp_indexAC_idx2_4 == indexAC_idx2_1) ? 1'b1 : 1'b0);

assign indexAC_idx2_5_fu_164_p2 = (ap_sig_allocacmp_indexAC_idx2_4 + 17'd1);

assign indexAC_idx2_cast_fu_117_p1 = indexAC_idx2;

assign start_colSelectionCount_1_fu_143_p2 = (ap_sig_allocacmp_start_colSelectionCount + 5'd1);

assign start_colSelection_1_address0 = zext_ln848_fu_186_p1;

assign start_colSelection_1_ce0 = start_colSelection_1_ce0_local;

assign start_colSelection_1_d0 = trunc_ln848_fu_180_p1;

assign start_colSelection_1_we0 = start_colSelection_1_we0_local;

assign trunc_ln147_fu_149_p1 = ap_sig_allocacmp_indexAC_idx2_4[15:0];

assign trunc_ln848_fu_180_p1 = unusableInfo_usableAtoms_data_q0[15:0];

assign unusableInfo_usableAtoms_data_address0 = zext_ln147_fu_159_p1;

assign unusableInfo_usableAtoms_data_ce0 = unusableInfo_usableAtoms_data_ce0_local;

assign zext_ln147_fu_159_p1 = add_ln147_fu_153_p2;

assign zext_ln848_fu_186_p1 = start_colSelectionCount_reg_205;

endmodule //atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_841_18
