// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln1274,
        trunc_ln24,
        empty,
        unusableInfo_targetSites_data_address0,
        unusableInfo_targetSites_data_ce0,
        unusableInfo_targetSites_data_q0,
        usedTargetIndices_data_address0,
        usedTargetIndices_data_ce0,
        usedTargetIndices_data_we0,
        usedTargetIndices_data_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] sext_ln1274;
input  [15:0] trunc_ln24;
input  [15:0] empty;
output  [15:0] unusableInfo_targetSites_data_address0;
output   unusableInfo_targetSites_data_ce0;
input  [7:0] unusableInfo_targetSites_data_q0;
output  [7:0] usedTargetIndices_data_address0;
output   usedTargetIndices_data_ce0;
output   usedTargetIndices_data_we0;
output  [7:0] usedTargetIndices_data_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln260_fu_121_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [63:0] sext_ln1274_cast_fu_101_p1;
reg  signed [63:0] sext_ln1274_cast_reg_195;
reg   [15:0] usedTargetIndices_count_1_reg_200;
wire   [63:0] zext_ln265_fu_146_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln265_1_fu_167_p1;
reg   [63:0] i_fu_48;
wire   [63:0] i_10_fu_151_p2;
wire    ap_loop_init;
reg   [15:0] usedTargetIndices_count_fu_52;
wire   [15:0] usedTargetIndices_count_2_fu_126_p2;
reg    unusableInfo_targetSites_data_ce0_local;
reg    usedTargetIndices_data_we0_local;
reg    usedTargetIndices_data_ce0_local;
wire   [15:0] trunc_ln1274_fu_132_p1;
wire   [15:0] add_ln265_1_fu_136_p2;
wire   [15:0] add_ln265_2_fu_141_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_48 = 64'd0;
#0 usedTargetIndices_count_fu_52 = 16'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 64'd0;
        end else if (((icmp_ln260_fu_121_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_48 <= i_10_fu_151_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            usedTargetIndices_count_fu_52 <= 16'd0;
        end else if (((icmp_ln260_fu_121_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            usedTargetIndices_count_fu_52 <= usedTargetIndices_count_2_fu_126_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln1274_cast_reg_195 <= sext_ln1274_cast_fu_101_p1;
        usedTargetIndices_count_1_reg_200 <= usedTargetIndices_count_fu_52;
    end
end

always @ (*) begin
    if (((icmp_ln260_fu_121_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unusableInfo_targetSites_data_ce0_local = 1'b1;
    end else begin
        unusableInfo_targetSites_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        usedTargetIndices_data_ce0_local = 1'b1;
    end else begin
        usedTargetIndices_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        usedTargetIndices_data_we0_local = 1'b1;
    end else begin
        usedTargetIndices_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln265_1_fu_136_p2 = (trunc_ln1274_fu_132_p1 + trunc_ln24);

assign add_ln265_2_fu_141_p2 = (empty + add_ln265_1_fu_136_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign i_10_fu_151_p2 = (i_fu_48 + 64'd1);

assign icmp_ln260_fu_121_p2 = ((i_fu_48 == sext_ln1274_cast_reg_195) ? 1'b1 : 1'b0);

assign sext_ln1274_cast_fu_101_p1 = $signed(sext_ln1274);

assign trunc_ln1274_fu_132_p1 = i_fu_48[15:0];

assign unusableInfo_targetSites_data_address0 = zext_ln265_fu_146_p1;

assign unusableInfo_targetSites_data_ce0 = unusableInfo_targetSites_data_ce0_local;

assign usedTargetIndices_count_2_fu_126_p2 = (usedTargetIndices_count_fu_52 + 16'd1);

assign usedTargetIndices_data_address0 = zext_ln265_1_fu_167_p1;

assign usedTargetIndices_data_ce0 = usedTargetIndices_data_ce0_local;

assign usedTargetIndices_data_d0 = unusableInfo_targetSites_data_q0;

assign usedTargetIndices_data_we0 = usedTargetIndices_data_we0_local;

assign zext_ln265_1_fu_167_p1 = usedTargetIndices_count_1_reg_200;

assign zext_ln265_fu_146_p1 = add_ln265_2_fu_141_p2;

endmodule //atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_14
