// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1114_37 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        usableFrontBuf_address0,
        usableFrontBuf_ce0,
        usableFrontBuf_q0,
        usableBackBuf_address0,
        usableBackBuf_ce0,
        usableBackBuf_q0,
        parkFrontBuf_address0,
        parkFrontBuf_ce0,
        parkFrontBuf_q0,
        parkBackBuf_address0,
        parkBackBuf_ce0,
        parkBackBuf_q0,
        start_colSelection_2_address0,
        start_colSelection_2_ce0,
        start_colSelection_2_we0,
        start_colSelection_2_d0,
        end_colSelection_2_address0,
        end_colSelection_2_ce0,
        end_colSelection_2_we0,
        end_colSelection_2_d0,
        prefetchCountParking_1,
        prefetchCountUsable,
        parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38,
        zext_ln882,
        requiredAtoms_2,
        iter_1_out,
        iter_1_out_ap_vld,
        parkingBackIdx_out,
        parkingBackIdx_out_ap_vld,
        parkingFrontIdx_out,
        parkingFrontIdx_out_ap_vld,
        usableBackIdx_out,
        usableBackIdx_out_ap_vld,
        usableFrontIdx_3_out,
        usableFrontIdx_3_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] usableFrontBuf_address0;
output   usableFrontBuf_ce0;
input  [31:0] usableFrontBuf_q0;
output  [3:0] usableBackBuf_address0;
output   usableBackBuf_ce0;
input  [31:0] usableBackBuf_q0;
output  [3:0] parkFrontBuf_address0;
output   parkFrontBuf_ce0;
input  [63:0] parkFrontBuf_q0;
output  [3:0] parkBackBuf_address0;
output   parkBackBuf_ce0;
input  [63:0] parkBackBuf_q0;
output  [3:0] start_colSelection_2_address0;
output   start_colSelection_2_ce0;
output   start_colSelection_2_we0;
output  [15:0] start_colSelection_2_d0;
output  [3:0] end_colSelection_2_address0;
output   end_colSelection_2_ce0;
output   end_colSelection_2_we0;
output  [15:0] end_colSelection_2_d0;
input  [4:0] prefetchCountParking_1;
input  [4:0] prefetchCountUsable;
input  [15:0] parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38;
input  [15:0] zext_ln882;
input  [15:0] requiredAtoms_2;
output  [4:0] iter_1_out;
output   iter_1_out_ap_vld;
output  [4:0] parkingBackIdx_out;
output   parkingBackIdx_out_ap_vld;
output  [4:0] parkingFrontIdx_out;
output   parkingFrontIdx_out_ap_vld;
output  [4:0] usableBackIdx_out;
output   usableBackIdx_out_ap_vld;
output  [4:0] usableFrontIdx_3_out;
output   usableFrontIdx_3_out_ap_vld;

reg ap_idle;
reg iter_1_out_ap_vld;
reg parkingBackIdx_out_ap_vld;
reg parkingFrontIdx_out_ap_vld;
reg usableBackIdx_out_ap_vld;
reg usableFrontIdx_3_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] or_ln1126_fu_445_p2;
wire   [0:0] or_ln1125_fu_415_p2;
wire   [0:0] icmp_ln1122_fu_385_p2;
wire   [0:0] icmp_ln1121_fu_365_p2;
wire   [0:0] tmp_fu_331_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] grp_fu_266_p1;
reg   [63:0] reg_271;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1133_reg_1260;
reg   [0:0] icmp_ln1133_reg_1260_pp0_iter3_reg;
wire   [63:0] grp_fu_261_p1;
reg   [63:0] reg_275;
reg   [4:0] iter_1_reg_1170;
reg   [4:0] iter_1_reg_1170_pp0_iter1_reg;
reg   [4:0] iter_1_reg_1170_pp0_iter2_reg;
reg   [4:0] iter_1_reg_1170_pp0_iter3_reg;
reg   [4:0] iter_1_reg_1170_pp0_iter4_reg;
reg   [4:0] usableFrontIdx_2_reg_1176;
reg   [4:0] usableFrontIdx_2_reg_1176_pp0_iter1_reg;
reg   [4:0] usableFrontIdx_2_reg_1176_pp0_iter2_reg;
reg   [4:0] usableFrontIdx_2_reg_1176_pp0_iter3_reg;
reg   [4:0] usableBackIdx_2_reg_1182;
reg   [4:0] usableBackIdx_2_reg_1182_pp0_iter1_reg;
reg   [4:0] usableBackIdx_2_reg_1182_pp0_iter2_reg;
reg   [4:0] usableBackIdx_2_reg_1182_pp0_iter3_reg;
reg   [4:0] parkingFrontIdx_2_reg_1188;
reg   [4:0] parkingFrontIdx_2_reg_1188_pp0_iter1_reg;
reg   [4:0] parkingFrontIdx_2_reg_1188_pp0_iter2_reg;
reg   [4:0] parkingFrontIdx_2_reg_1188_pp0_iter3_reg;
reg   [4:0] parkingBackIdx_2_reg_1194;
reg   [4:0] parkingBackIdx_2_reg_1194_pp0_iter1_reg;
reg   [4:0] parkingBackIdx_2_reg_1194_pp0_iter2_reg;
reg   [4:0] parkingBackIdx_2_reg_1194_pp0_iter3_reg;
reg   [0:0] tmp_reg_1200;
reg   [0:0] tmp_reg_1200_pp0_iter1_reg;
reg   [0:0] tmp_reg_1200_pp0_iter2_reg;
reg   [0:0] icmp_ln1121_reg_1204;
reg   [0:0] icmp_ln1121_reg_1204_pp0_iter1_reg;
reg   [0:0] icmp_ln1121_reg_1204_pp0_iter2_reg;
reg   [0:0] icmp_ln1122_reg_1208;
reg   [0:0] icmp_ln1122_reg_1208_pp0_iter1_reg;
reg   [0:0] icmp_ln1122_reg_1208_pp0_iter2_reg;
reg   [0:0] or_ln1125_reg_1212;
reg   [0:0] or_ln1125_reg_1212_pp0_iter1_reg;
reg   [0:0] or_ln1125_reg_1212_pp0_iter2_reg;
reg   [0:0] or_ln1126_reg_1216;
reg   [0:0] or_ln1126_reg_1216_pp0_iter1_reg;
reg   [0:0] or_ln1126_reg_1216_pp0_iter2_reg;
wire   [0:0] icmp_ln1133_fu_536_p2;
reg   [0:0] icmp_ln1133_reg_1260_pp0_iter2_reg;
reg   [0:0] icmp_ln1133_reg_1260_pp0_iter4_reg;
wire   [63:0] zext_ln1128_fu_451_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1129_fu_456_p1;
wire   [63:0] zext_ln1130_fu_461_p1;
wire   [63:0] zext_ln1131_fu_466_p1;
wire   [63:0] zext_ln1142_fu_582_p1;
reg   [4:0] iter_fu_98;
wire   [4:0] iter_2_fu_339_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_iter_1;
reg   [4:0] usableFrontIdx_1_fu_102;
wire   [4:0] usableFrontIdx_fu_562_p2;
reg   [4:0] ap_sig_allocacmp_usableFrontIdx_2;
reg   [4:0] usableBackIdx_fu_106;
wire   [4:0] usableBackIdx_3_fu_542_p2;
reg   [4:0] ap_sig_allocacmp_usableBackIdx_2;
reg   [4:0] parkingFrontIdx_fu_110;
wire   [4:0] parkingFrontIdx_3_fu_567_p2;
reg   [4:0] ap_sig_allocacmp_parkingFrontIdx_2;
reg   [4:0] parkingBackIdx_fu_114;
wire   [4:0] parkingBackIdx_3_fu_547_p2;
reg   [4:0] ap_sig_allocacmp_parkingBackIdx_2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
wire    ap_block_pp0_stage0_01001;
reg    ap_predicate_pred308_state5;
reg    usableFrontBuf_ce0_local;
reg    usableBackBuf_ce0_local;
reg    parkFrontBuf_ce0_local;
reg    parkBackBuf_ce0_local;
reg    start_colSelection_2_we0_local;
reg   [15:0] start_colSelection_2_d0_local;
wire   [15:0] result_5_fu_715_p3;
reg    start_colSelection_2_ce0_local;
wire   [15:0] result_1_fu_989_p3;
reg    end_colSelection_2_we0_local;
reg   [15:0] end_colSelection_2_d0_local;
wire   [15:0] result_7_fu_852_p3;
reg    end_colSelection_2_ce0_local;
wire   [15:0] result_3_fu_1126_p3;
reg   [63:0] grp_fu_261_p0;
reg   [31:0] grp_fu_266_p0;
wire   [16:0] zext_ln882_cast_fu_279_p1;
wire   [16:0] zext_ln1121_1_fu_349_p1;
wire   [16:0] sub_ln1121_fu_353_p2;
wire   [16:0] zext_ln1121_fu_345_p1;
wire   [16:0] sub_ln1121_1_fu_359_p2;
wire   [16:0] requiredAtoms_2_cast_fu_287_p1;
wire   [16:0] parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38_cast_fu_283_p1;
wire   [16:0] zext_ln1122_fu_371_p1;
wire   [16:0] sub_ln1122_fu_375_p2;
wire   [16:0] zext_ln1122_1_fu_381_p1;
wire   [0:0] icmp_ln1125_fu_391_p2;
wire   [0:0] icmp_ln1125_1_fu_403_p2;
wire   [0:0] xor_ln1125_fu_397_p2;
wire   [0:0] xor_ln1125_1_fu_409_p2;
wire   [0:0] icmp_ln1126_fu_421_p2;
wire   [0:0] icmp_ln1126_1_fu_433_p2;
wire   [0:0] xor_ln1126_fu_427_p2;
wire   [0:0] xor_ln1126_1_fu_439_p2;
wire   [31:0] trunc_ln1133_fu_476_p1;
wire   [31:0] sub_ln1133_fu_480_p2;
wire   [0:0] abscond_fu_492_p2;
wire   [31:0] neg_fu_486_p2;
wire   [31:0] trunc_ln1133_1_fu_506_p1;
wire   [31:0] sub_ln1133_1_fu_510_p2;
wire   [0:0] abscond83_fu_522_p2;
wire   [31:0] neg82_fu_516_p2;
wire   [31:0] abs_fu_498_p3;
wire   [31:0] abs84_fu_528_p3;
wire   [63:0] data_2_fu_587_p1;
wire   [51:0] trunc_ln505_2_fu_607_p1;
wire   [53:0] mantissa_2_fu_611_p4;
wire   [10:0] xs_exp_2_fu_599_p3;
wire   [11:0] zext_ln486_2_fu_625_p1;
wire   [11:0] add_ln486_2_fu_629_p2;
wire   [10:0] sub_ln18_2_fu_643_p2;
wire   [0:0] tmp_11_fu_635_p3;
wire  signed [11:0] sext_ln18_4_fu_649_p1;
wire   [11:0] select_ln18_4_fu_653_p3;
wire  signed [31:0] sext_ln18_5_fu_661_p1;
wire   [120:0] zext_ln15_2_fu_621_p1;
wire   [120:0] zext_ln18_2_fu_665_p1;
wire   [120:0] lshr_ln18_2_fu_669_p2;
wire   [120:0] shl_ln18_2_fu_675_p2;
wire   [15:0] tmp_10_fu_681_p4;
wire   [15:0] tmp_12_fu_691_p4;
wire   [15:0] val_2_fu_701_p3;
wire   [0:0] xs_sign_2_fu_591_p3;
wire   [15:0] sub_ln59_2_fu_709_p2;
wire   [63:0] data_3_fu_724_p1;
wire   [51:0] trunc_ln505_3_fu_744_p1;
wire   [53:0] mantissa_3_fu_748_p4;
wire   [10:0] xs_exp_3_fu_736_p3;
wire   [11:0] zext_ln486_3_fu_762_p1;
wire   [11:0] add_ln486_3_fu_766_p2;
wire   [10:0] sub_ln18_3_fu_780_p2;
wire   [0:0] tmp_14_fu_772_p3;
wire  signed [11:0] sext_ln18_6_fu_786_p1;
wire   [11:0] select_ln18_6_fu_790_p3;
wire  signed [31:0] sext_ln18_7_fu_798_p1;
wire   [120:0] zext_ln15_3_fu_758_p1;
wire   [120:0] zext_ln18_3_fu_802_p1;
wire   [120:0] lshr_ln18_3_fu_806_p2;
wire   [120:0] shl_ln18_3_fu_812_p2;
wire   [15:0] tmp_13_fu_818_p4;
wire   [15:0] tmp_15_fu_828_p4;
wire   [15:0] val_3_fu_838_p3;
wire   [0:0] xs_sign_3_fu_728_p3;
wire   [15:0] sub_ln59_3_fu_846_p2;
wire   [63:0] data_fu_861_p1;
wire   [51:0] trunc_ln505_fu_881_p1;
wire   [53:0] mantissa_fu_885_p4;
wire   [10:0] xs_exp_fu_873_p3;
wire   [11:0] zext_ln486_fu_899_p1;
wire   [11:0] add_ln486_fu_903_p2;
wire   [10:0] sub_ln18_fu_917_p2;
wire   [0:0] tmp_7_fu_909_p3;
wire  signed [11:0] sext_ln18_fu_923_p1;
wire   [11:0] select_ln18_fu_927_p3;
wire  signed [31:0] sext_ln18_1_fu_935_p1;
wire   [120:0] zext_ln15_fu_895_p1;
wire   [120:0] zext_ln18_fu_939_p1;
wire   [120:0] lshr_ln18_fu_943_p2;
wire   [120:0] shl_ln18_fu_949_p2;
wire   [15:0] tmp_s_fu_955_p4;
wire   [15:0] tmp_5_fu_965_p4;
wire   [15:0] val_fu_975_p3;
wire   [0:0] xs_sign_fu_865_p3;
wire   [15:0] sub_ln59_fu_983_p2;
wire   [63:0] data_1_fu_998_p1;
wire   [51:0] trunc_ln505_1_fu_1018_p1;
wire   [53:0] mantissa_1_fu_1022_p4;
wire   [10:0] xs_exp_1_fu_1010_p3;
wire   [11:0] zext_ln486_1_fu_1036_p1;
wire   [11:0] add_ln486_1_fu_1040_p2;
wire   [10:0] sub_ln18_1_fu_1054_p2;
wire   [0:0] tmp_9_fu_1046_p3;
wire  signed [11:0] sext_ln18_2_fu_1060_p1;
wire   [11:0] select_ln18_2_fu_1064_p3;
wire  signed [31:0] sext_ln18_3_fu_1072_p1;
wire   [120:0] zext_ln15_1_fu_1032_p1;
wire   [120:0] zext_ln18_1_fu_1076_p1;
wire   [120:0] lshr_ln18_1_fu_1080_p2;
wire   [120:0] shl_ln18_1_fu_1086_p2;
wire   [15:0] tmp_6_fu_1092_p4;
wire   [15:0] tmp_8_fu_1102_p4;
wire   [15:0] val_1_fu_1112_p3;
wire   [0:0] xs_sign_1_fu_1002_p3;
wire   [15:0] sub_ln59_1_fu_1120_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_271;
reg    ap_condition_905;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 iter_fu_98 = 5'd0;
#0 usableFrontIdx_1_fu_102 = 5'd0;
#0 usableBackIdx_fu_106 = 5'd0;
#0 parkingFrontIdx_fu_110 = 5'd0;
#0 parkingBackIdx_fu_114 = 5'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_uitodp_64ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
uitodp_64ns_64_4_no_dsp_1_U746(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_261_p0),
    .ce(1'b1),
    .dout(grp_fu_261_p1)
);

atomflow_controller_sitodp_32ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_4_no_dsp_1_U747(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_266_p0),
    .ce(1'b1),
    .dout(grp_fu_266_p1)
);

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_905)) begin
            iter_fu_98 <= iter_2_fu_339_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            iter_fu_98 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            parkingBackIdx_fu_114 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd0))) begin
            parkingBackIdx_fu_114 <= parkingBackIdx_3_fu_547_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            parkingFrontIdx_fu_110 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd1))) begin
            parkingFrontIdx_fu_110 <= parkingFrontIdx_3_fu_567_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            usableBackIdx_fu_106 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd0))) begin
            usableBackIdx_fu_106 <= usableBackIdx_3_fu_542_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            usableFrontIdx_1_fu_102 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd1))) begin
            usableFrontIdx_1_fu_102 <= usableFrontIdx_fu_562_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1121_reg_1204 <= icmp_ln1121_fu_365_p2;
        icmp_ln1121_reg_1204_pp0_iter1_reg <= icmp_ln1121_reg_1204;
        icmp_ln1122_reg_1208 <= icmp_ln1122_fu_385_p2;
        icmp_ln1122_reg_1208_pp0_iter1_reg <= icmp_ln1122_reg_1208;
        icmp_ln1133_reg_1260 <= icmp_ln1133_fu_536_p2;
        iter_1_reg_1170_pp0_iter1_reg <= iter_1_reg_1170;
        or_ln1125_reg_1212 <= or_ln1125_fu_415_p2;
        or_ln1125_reg_1212_pp0_iter1_reg <= or_ln1125_reg_1212;
        or_ln1126_reg_1216 <= or_ln1126_fu_445_p2;
        or_ln1126_reg_1216_pp0_iter1_reg <= or_ln1126_reg_1216;
        parkingBackIdx_2_reg_1194_pp0_iter1_reg <= parkingBackIdx_2_reg_1194;
        parkingFrontIdx_2_reg_1188_pp0_iter1_reg <= parkingFrontIdx_2_reg_1188;
        tmp_reg_1200 <= ap_sig_allocacmp_iter_1[32'd4];
        tmp_reg_1200_pp0_iter1_reg <= tmp_reg_1200;
        usableBackIdx_2_reg_1182_pp0_iter1_reg <= usableBackIdx_2_reg_1182;
        usableFrontIdx_2_reg_1176_pp0_iter1_reg <= usableFrontIdx_2_reg_1176;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_predicate_pred308_state5 <= ((tmp_reg_1200_pp0_iter2_reg == 1'd1) | ((icmp_ln1121_reg_1204_pp0_iter2_reg == 1'd0) | ((icmp_ln1122_reg_1208_pp0_iter2_reg == 1'd1) | ((or_ln1126_reg_1216_pp0_iter2_reg == 1'd1) | (or_ln1125_reg_1212_pp0_iter2_reg == 1'd1)))));
        icmp_ln1121_reg_1204_pp0_iter2_reg <= icmp_ln1121_reg_1204_pp0_iter1_reg;
        icmp_ln1122_reg_1208_pp0_iter2_reg <= icmp_ln1122_reg_1208_pp0_iter1_reg;
        icmp_ln1133_reg_1260_pp0_iter2_reg <= icmp_ln1133_reg_1260;
        icmp_ln1133_reg_1260_pp0_iter3_reg <= icmp_ln1133_reg_1260_pp0_iter2_reg;
        icmp_ln1133_reg_1260_pp0_iter4_reg <= icmp_ln1133_reg_1260_pp0_iter3_reg;
        iter_1_reg_1170_pp0_iter2_reg <= iter_1_reg_1170_pp0_iter1_reg;
        iter_1_reg_1170_pp0_iter3_reg <= iter_1_reg_1170_pp0_iter2_reg;
        iter_1_reg_1170_pp0_iter4_reg <= iter_1_reg_1170_pp0_iter3_reg;
        or_ln1125_reg_1212_pp0_iter2_reg <= or_ln1125_reg_1212_pp0_iter1_reg;
        or_ln1126_reg_1216_pp0_iter2_reg <= or_ln1126_reg_1216_pp0_iter1_reg;
        parkingBackIdx_2_reg_1194_pp0_iter2_reg <= parkingBackIdx_2_reg_1194_pp0_iter1_reg;
        parkingBackIdx_2_reg_1194_pp0_iter3_reg <= parkingBackIdx_2_reg_1194_pp0_iter2_reg;
        parkingFrontIdx_2_reg_1188_pp0_iter2_reg <= parkingFrontIdx_2_reg_1188_pp0_iter1_reg;
        parkingFrontIdx_2_reg_1188_pp0_iter3_reg <= parkingFrontIdx_2_reg_1188_pp0_iter2_reg;
        tmp_reg_1200_pp0_iter2_reg <= tmp_reg_1200_pp0_iter1_reg;
        usableBackIdx_2_reg_1182_pp0_iter2_reg <= usableBackIdx_2_reg_1182_pp0_iter1_reg;
        usableBackIdx_2_reg_1182_pp0_iter3_reg <= usableBackIdx_2_reg_1182_pp0_iter2_reg;
        usableFrontIdx_2_reg_1176_pp0_iter2_reg <= usableFrontIdx_2_reg_1176_pp0_iter1_reg;
        usableFrontIdx_2_reg_1176_pp0_iter3_reg <= usableFrontIdx_2_reg_1176_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        iter_1_reg_1170 <= ap_sig_allocacmp_iter_1;
        parkingBackIdx_2_reg_1194 <= ap_sig_allocacmp_parkingBackIdx_2;
        parkingFrontIdx_2_reg_1188 <= ap_sig_allocacmp_parkingFrontIdx_2;
        usableBackIdx_2_reg_1182 <= ap_sig_allocacmp_usableBackIdx_2;
        usableFrontIdx_2_reg_1176 <= ap_sig_allocacmp_usableFrontIdx_2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter3_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter3_reg == 1'd0)))) begin
        reg_271 <= grp_fu_266_p1;
        reg_275 <= grp_fu_261_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((tmp_fu_331_p3 == 1'd1) | ((icmp_ln1121_fu_365_p2 == 1'd0) | ((icmp_ln1122_fu_385_p2 == 1'd1) | ((or_ln1125_fu_415_p2 == 1'd1) | (or_ln1126_fu_445_p2 == 1'd1))))))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_iter_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_iter_1 = iter_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_parkingBackIdx_2 = 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd0))) begin
            ap_sig_allocacmp_parkingBackIdx_2 = parkingBackIdx_3_fu_547_p2;
        end else begin
            ap_sig_allocacmp_parkingBackIdx_2 = parkingBackIdx_fu_114;
        end
    end else begin
        ap_sig_allocacmp_parkingBackIdx_2 = parkingBackIdx_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_parkingFrontIdx_2 = 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd1))) begin
            ap_sig_allocacmp_parkingFrontIdx_2 = parkingFrontIdx_3_fu_567_p2;
        end else begin
            ap_sig_allocacmp_parkingFrontIdx_2 = parkingFrontIdx_fu_110;
        end
    end else begin
        ap_sig_allocacmp_parkingFrontIdx_2 = parkingFrontIdx_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_usableBackIdx_2 = 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd0))) begin
            ap_sig_allocacmp_usableBackIdx_2 = usableBackIdx_3_fu_542_p2;
        end else begin
            ap_sig_allocacmp_usableBackIdx_2 = usableBackIdx_fu_106;
        end
    end else begin
        ap_sig_allocacmp_usableBackIdx_2 = usableBackIdx_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_usableFrontIdx_2 = 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1133_fu_536_p2 == 1'd1))) begin
            ap_sig_allocacmp_usableFrontIdx_2 = usableFrontIdx_fu_562_p2;
        end else begin
            ap_sig_allocacmp_usableFrontIdx_2 = usableFrontIdx_1_fu_102;
        end
    end else begin
        ap_sig_allocacmp_usableFrontIdx_2 = usableFrontIdx_1_fu_102;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)))) begin
        end_colSelection_2_ce0_local = 1'b1;
    end else begin
        end_colSelection_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) begin
            end_colSelection_2_d0_local = result_3_fu_1126_p3;
        end else if ((icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)) begin
            end_colSelection_2_d0_local = result_7_fu_852_p3;
        end else begin
            end_colSelection_2_d0_local = 'bx;
        end
    end else begin
        end_colSelection_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)))) begin
        end_colSelection_2_we0_local = 1'b1;
    end else begin
        end_colSelection_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_271)) begin
        if ((icmp_ln1133_fu_536_p2 == 1'd1)) begin
            grp_fu_261_p0 = parkFrontBuf_q0;
        end else if ((icmp_ln1133_fu_536_p2 == 1'd0)) begin
            grp_fu_261_p0 = parkBackBuf_q0;
        end else begin
            grp_fu_261_p0 = 'bx;
        end
    end else begin
        grp_fu_261_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_271)) begin
        if ((icmp_ln1133_fu_536_p2 == 1'd1)) begin
            grp_fu_266_p0 = usableFrontBuf_q0;
        end else if ((icmp_ln1133_fu_536_p2 == 1'd0)) begin
            grp_fu_266_p0 = usableBackBuf_q0;
        end else begin
            grp_fu_266_p0 = 'bx;
        end
    end else begin
        grp_fu_266_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred308_state5 == 1'b1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        iter_1_out_ap_vld = 1'b1;
    end else begin
        iter_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        parkBackBuf_ce0_local = 1'b1;
    end else begin
        parkBackBuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        parkFrontBuf_ce0_local = 1'b1;
    end else begin
        parkFrontBuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred308_state5 == 1'b1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        parkingBackIdx_out_ap_vld = 1'b1;
    end else begin
        parkingBackIdx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred308_state5 == 1'b1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        parkingFrontIdx_out_ap_vld = 1'b1;
    end else begin
        parkingFrontIdx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)))) begin
        start_colSelection_2_ce0_local = 1'b1;
    end else begin
        start_colSelection_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) begin
            start_colSelection_2_d0_local = result_1_fu_989_p3;
        end else if ((icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)) begin
            start_colSelection_2_d0_local = result_5_fu_715_p3;
        end else begin
            start_colSelection_2_d0_local = 'bx;
        end
    end else begin
        start_colSelection_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1133_reg_1260_pp0_iter4_reg == 1'd0)))) begin
        start_colSelection_2_we0_local = 1'b1;
    end else begin
        start_colSelection_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        usableBackBuf_ce0_local = 1'b1;
    end else begin
        usableBackBuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred308_state5 == 1'b1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        usableBackIdx_out_ap_vld = 1'b1;
    end else begin
        usableBackIdx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        usableFrontBuf_ce0_local = 1'b1;
    end else begin
        usableFrontBuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred308_state5 == 1'b1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        usableFrontIdx_3_out_ap_vld = 1'b1;
    end else begin
        usableFrontIdx_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs84_fu_528_p3 = ((abscond83_fu_522_p2[0:0] == 1'b1) ? sub_ln1133_1_fu_510_p2 : neg82_fu_516_p2);

assign abs_fu_498_p3 = ((abscond_fu_492_p2[0:0] == 1'b1) ? sub_ln1133_fu_480_p2 : neg_fu_486_p2);

assign abscond83_fu_522_p2 = (($signed(sub_ln1133_1_fu_510_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_492_p2 = (($signed(sub_ln1133_fu_480_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign add_ln486_1_fu_1040_p2 = ($signed(zext_ln486_1_fu_1036_p1) + $signed(12'd3073));

assign add_ln486_2_fu_629_p2 = ($signed(zext_ln486_2_fu_625_p1) + $signed(12'd3073));

assign add_ln486_3_fu_766_p2 = ($signed(zext_ln486_3_fu_762_p1) + $signed(12'd3073));

assign add_ln486_fu_903_p2 = ($signed(zext_ln486_fu_899_p1) + $signed(12'd3073));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_271 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_905 = ((tmp_fu_331_p3 == 1'd0) & (icmp_ln1121_fu_365_p2 == 1'd1) & (icmp_ln1122_fu_385_p2 == 1'd0) & (or_ln1125_fu_415_p2 == 1'd0) & (or_ln1126_fu_445_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign data_1_fu_998_p1 = reg_275;

assign data_2_fu_587_p1 = reg_271;

assign data_3_fu_724_p1 = reg_275;

assign data_fu_861_p1 = reg_271;

assign end_colSelection_2_address0 = zext_ln1142_fu_582_p1;

assign end_colSelection_2_ce0 = end_colSelection_2_ce0_local;

assign end_colSelection_2_d0 = end_colSelection_2_d0_local;

assign end_colSelection_2_we0 = end_colSelection_2_we0_local;

assign icmp_ln1121_fu_365_p2 = ((sub_ln1121_1_fu_359_p2 > requiredAtoms_2_cast_fu_287_p1) ? 1'b1 : 1'b0);

assign icmp_ln1122_fu_385_p2 = ((sub_ln1122_fu_375_p2 == zext_ln1122_1_fu_381_p1) ? 1'b1 : 1'b0);

assign icmp_ln1125_1_fu_403_p2 = ((ap_sig_allocacmp_usableBackIdx_2 < prefetchCountUsable) ? 1'b1 : 1'b0);

assign icmp_ln1125_fu_391_p2 = ((ap_sig_allocacmp_usableFrontIdx_2 < prefetchCountUsable) ? 1'b1 : 1'b0);

assign icmp_ln1126_1_fu_433_p2 = ((ap_sig_allocacmp_parkingBackIdx_2 < prefetchCountParking_1) ? 1'b1 : 1'b0);

assign icmp_ln1126_fu_421_p2 = ((ap_sig_allocacmp_parkingFrontIdx_2 < prefetchCountParking_1) ? 1'b1 : 1'b0);

assign icmp_ln1133_fu_536_p2 = (($signed(abs_fu_498_p3) < $signed(abs84_fu_528_p3)) ? 1'b1 : 1'b0);

assign iter_1_out = iter_1_reg_1170_pp0_iter3_reg;

assign iter_2_fu_339_p2 = (ap_sig_allocacmp_iter_1 + 5'd1);

assign lshr_ln18_1_fu_1080_p2 = zext_ln15_1_fu_1032_p1 >> zext_ln18_1_fu_1076_p1;

assign lshr_ln18_2_fu_669_p2 = zext_ln15_2_fu_621_p1 >> zext_ln18_2_fu_665_p1;

assign lshr_ln18_3_fu_806_p2 = zext_ln15_3_fu_758_p1 >> zext_ln18_3_fu_802_p1;

assign lshr_ln18_fu_943_p2 = zext_ln15_fu_895_p1 >> zext_ln18_fu_939_p1;

assign mantissa_1_fu_1022_p4 = {{{{1'd1}, {trunc_ln505_1_fu_1018_p1}}}, {1'd0}};

assign mantissa_2_fu_611_p4 = {{{{1'd1}, {trunc_ln505_2_fu_607_p1}}}, {1'd0}};

assign mantissa_3_fu_748_p4 = {{{{1'd1}, {trunc_ln505_3_fu_744_p1}}}, {1'd0}};

assign mantissa_fu_885_p4 = {{{{1'd1}, {trunc_ln505_fu_881_p1}}}, {1'd0}};

assign neg82_fu_516_p2 = (32'd0 - sub_ln1133_1_fu_510_p2);

assign neg_fu_486_p2 = (32'd0 - sub_ln1133_fu_480_p2);

assign or_ln1125_fu_415_p2 = (xor_ln1125_fu_397_p2 | xor_ln1125_1_fu_409_p2);

assign or_ln1126_fu_445_p2 = (xor_ln1126_fu_427_p2 | xor_ln1126_1_fu_439_p2);

assign parkBackBuf_address0 = zext_ln1131_fu_466_p1;

assign parkBackBuf_ce0 = parkBackBuf_ce0_local;

assign parkFrontBuf_address0 = zext_ln1130_fu_461_p1;

assign parkFrontBuf_ce0 = parkFrontBuf_ce0_local;

assign parkingBackIdx_3_fu_547_p2 = (parkingBackIdx_2_reg_1194 + 5'd1);

assign parkingBackIdx_out = parkingBackIdx_2_reg_1194_pp0_iter3_reg;

assign parkingFrontIdx_3_fu_567_p2 = (parkingFrontIdx_2_reg_1188 + 5'd1);

assign parkingFrontIdx_out = parkingFrontIdx_2_reg_1188_pp0_iter3_reg;

assign parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38_cast_fu_283_p1 = parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38;

assign requiredAtoms_2_cast_fu_287_p1 = requiredAtoms_2;

assign result_1_fu_989_p3 = ((xs_sign_fu_865_p3[0:0] == 1'b1) ? sub_ln59_fu_983_p2 : val_fu_975_p3);

assign result_3_fu_1126_p3 = ((xs_sign_1_fu_1002_p3[0:0] == 1'b1) ? sub_ln59_1_fu_1120_p2 : val_1_fu_1112_p3);

assign result_5_fu_715_p3 = ((xs_sign_2_fu_591_p3[0:0] == 1'b1) ? sub_ln59_2_fu_709_p2 : val_2_fu_701_p3);

assign result_7_fu_852_p3 = ((xs_sign_3_fu_728_p3[0:0] == 1'b1) ? sub_ln59_3_fu_846_p2 : val_3_fu_838_p3);

assign select_ln18_2_fu_1064_p3 = ((tmp_9_fu_1046_p3[0:0] == 1'b1) ? sext_ln18_2_fu_1060_p1 : add_ln486_1_fu_1040_p2);

assign select_ln18_4_fu_653_p3 = ((tmp_11_fu_635_p3[0:0] == 1'b1) ? sext_ln18_4_fu_649_p1 : add_ln486_2_fu_629_p2);

assign select_ln18_6_fu_790_p3 = ((tmp_14_fu_772_p3[0:0] == 1'b1) ? sext_ln18_6_fu_786_p1 : add_ln486_3_fu_766_p2);

assign select_ln18_fu_927_p3 = ((tmp_7_fu_909_p3[0:0] == 1'b1) ? sext_ln18_fu_923_p1 : add_ln486_fu_903_p2);

assign sext_ln18_1_fu_935_p1 = $signed(select_ln18_fu_927_p3);

assign sext_ln18_2_fu_1060_p1 = $signed(sub_ln18_1_fu_1054_p2);

assign sext_ln18_3_fu_1072_p1 = $signed(select_ln18_2_fu_1064_p3);

assign sext_ln18_4_fu_649_p1 = $signed(sub_ln18_2_fu_643_p2);

assign sext_ln18_5_fu_661_p1 = $signed(select_ln18_4_fu_653_p3);

assign sext_ln18_6_fu_786_p1 = $signed(sub_ln18_3_fu_780_p2);

assign sext_ln18_7_fu_798_p1 = $signed(select_ln18_6_fu_790_p3);

assign sext_ln18_fu_923_p1 = $signed(sub_ln18_fu_917_p2);

assign shl_ln18_1_fu_1086_p2 = zext_ln15_1_fu_1032_p1 << zext_ln18_1_fu_1076_p1;

assign shl_ln18_2_fu_675_p2 = zext_ln15_2_fu_621_p1 << zext_ln18_2_fu_665_p1;

assign shl_ln18_3_fu_812_p2 = zext_ln15_3_fu_758_p1 << zext_ln18_3_fu_802_p1;

assign shl_ln18_fu_949_p2 = zext_ln15_fu_895_p1 << zext_ln18_fu_939_p1;

assign start_colSelection_2_address0 = zext_ln1142_fu_582_p1;

assign start_colSelection_2_ce0 = start_colSelection_2_ce0_local;

assign start_colSelection_2_d0 = start_colSelection_2_d0_local;

assign start_colSelection_2_we0 = start_colSelection_2_we0_local;

assign sub_ln1121_1_fu_359_p2 = (sub_ln1121_fu_353_p2 - zext_ln1121_fu_345_p1);

assign sub_ln1121_fu_353_p2 = (zext_ln882_cast_fu_279_p1 - zext_ln1121_1_fu_349_p1);

assign sub_ln1122_fu_375_p2 = (parkingSpotsRemainingAtCurrentIndexXC_count_7_cast38_cast_fu_283_p1 - zext_ln1122_fu_371_p1);

assign sub_ln1133_1_fu_510_p2 = (usableBackBuf_q0 - trunc_ln1133_1_fu_506_p1);

assign sub_ln1133_fu_480_p2 = (usableFrontBuf_q0 - trunc_ln1133_fu_476_p1);

assign sub_ln18_1_fu_1054_p2 = (11'd1023 - xs_exp_1_fu_1010_p3);

assign sub_ln18_2_fu_643_p2 = (11'd1023 - xs_exp_2_fu_599_p3);

assign sub_ln18_3_fu_780_p2 = (11'd1023 - xs_exp_3_fu_736_p3);

assign sub_ln18_fu_917_p2 = (11'd1023 - xs_exp_fu_873_p3);

assign sub_ln59_1_fu_1120_p2 = (16'd0 - val_1_fu_1112_p3);

assign sub_ln59_2_fu_709_p2 = (16'd0 - val_2_fu_701_p3);

assign sub_ln59_3_fu_846_p2 = (16'd0 - val_3_fu_838_p3);

assign sub_ln59_fu_983_p2 = (16'd0 - val_fu_975_p3);

assign tmp_10_fu_681_p4 = {{lshr_ln18_2_fu_669_p2[68:53]}};

assign tmp_11_fu_635_p3 = add_ln486_2_fu_629_p2[32'd11];

assign tmp_12_fu_691_p4 = {{shl_ln18_2_fu_675_p2[68:53]}};

assign tmp_13_fu_818_p4 = {{lshr_ln18_3_fu_806_p2[68:53]}};

assign tmp_14_fu_772_p3 = add_ln486_3_fu_766_p2[32'd11];

assign tmp_15_fu_828_p4 = {{shl_ln18_3_fu_812_p2[68:53]}};

assign tmp_5_fu_965_p4 = {{shl_ln18_fu_949_p2[68:53]}};

assign tmp_6_fu_1092_p4 = {{lshr_ln18_1_fu_1080_p2[68:53]}};

assign tmp_7_fu_909_p3 = add_ln486_fu_903_p2[32'd11];

assign tmp_8_fu_1102_p4 = {{shl_ln18_1_fu_1086_p2[68:53]}};

assign tmp_9_fu_1046_p3 = add_ln486_1_fu_1040_p2[32'd11];

assign tmp_fu_331_p3 = ap_sig_allocacmp_iter_1[32'd4];

assign tmp_s_fu_955_p4 = {{lshr_ln18_fu_943_p2[68:53]}};

assign trunc_ln1133_1_fu_506_p1 = parkBackBuf_q0[31:0];

assign trunc_ln1133_fu_476_p1 = parkFrontBuf_q0[31:0];

assign trunc_ln505_1_fu_1018_p1 = data_1_fu_998_p1[51:0];

assign trunc_ln505_2_fu_607_p1 = data_2_fu_587_p1[51:0];

assign trunc_ln505_3_fu_744_p1 = data_3_fu_724_p1[51:0];

assign trunc_ln505_fu_881_p1 = data_fu_861_p1[51:0];

assign usableBackBuf_address0 = zext_ln1129_fu_456_p1;

assign usableBackBuf_ce0 = usableBackBuf_ce0_local;

assign usableBackIdx_3_fu_542_p2 = (usableBackIdx_2_reg_1182 + 5'd1);

assign usableBackIdx_out = usableBackIdx_2_reg_1182_pp0_iter3_reg;

assign usableFrontBuf_address0 = zext_ln1128_fu_451_p1;

assign usableFrontBuf_ce0 = usableFrontBuf_ce0_local;

assign usableFrontIdx_3_out = usableFrontIdx_2_reg_1176_pp0_iter3_reg;

assign usableFrontIdx_fu_562_p2 = (usableFrontIdx_2_reg_1176 + 5'd1);

assign val_1_fu_1112_p3 = ((tmp_9_fu_1046_p3[0:0] == 1'b1) ? tmp_6_fu_1092_p4 : tmp_8_fu_1102_p4);

assign val_2_fu_701_p3 = ((tmp_11_fu_635_p3[0:0] == 1'b1) ? tmp_10_fu_681_p4 : tmp_12_fu_691_p4);

assign val_3_fu_838_p3 = ((tmp_14_fu_772_p3[0:0] == 1'b1) ? tmp_13_fu_818_p4 : tmp_15_fu_828_p4);

assign val_fu_975_p3 = ((tmp_7_fu_909_p3[0:0] == 1'b1) ? tmp_s_fu_955_p4 : tmp_5_fu_965_p4);

assign xor_ln1125_1_fu_409_p2 = (icmp_ln1125_1_fu_403_p2 ^ 1'd1);

assign xor_ln1125_fu_397_p2 = (icmp_ln1125_fu_391_p2 ^ 1'd1);

assign xor_ln1126_1_fu_439_p2 = (icmp_ln1126_1_fu_433_p2 ^ 1'd1);

assign xor_ln1126_fu_427_p2 = (icmp_ln1126_fu_421_p2 ^ 1'd1);

assign xs_exp_1_fu_1010_p3 = {{data_1_fu_998_p1[62:52]}};

assign xs_exp_2_fu_599_p3 = {{data_2_fu_587_p1[62:52]}};

assign xs_exp_3_fu_736_p3 = {{data_3_fu_724_p1[62:52]}};

assign xs_exp_fu_873_p3 = {{data_fu_861_p1[62:52]}};

assign xs_sign_1_fu_1002_p3 = data_1_fu_998_p1[32'd63];

assign xs_sign_2_fu_591_p3 = data_2_fu_587_p1[32'd63];

assign xs_sign_3_fu_728_p3 = data_3_fu_724_p1[32'd63];

assign xs_sign_fu_865_p3 = data_fu_861_p1[32'd63];

assign zext_ln1121_1_fu_349_p1 = ap_sig_allocacmp_usableBackIdx_2;

assign zext_ln1121_fu_345_p1 = ap_sig_allocacmp_usableFrontIdx_2;

assign zext_ln1122_1_fu_381_p1 = ap_sig_allocacmp_parkingBackIdx_2;

assign zext_ln1122_fu_371_p1 = ap_sig_allocacmp_parkingFrontIdx_2;

assign zext_ln1128_fu_451_p1 = ap_sig_allocacmp_usableFrontIdx_2;

assign zext_ln1129_fu_456_p1 = ap_sig_allocacmp_usableBackIdx_2;

assign zext_ln1130_fu_461_p1 = ap_sig_allocacmp_parkingFrontIdx_2;

assign zext_ln1131_fu_466_p1 = ap_sig_allocacmp_parkingBackIdx_2;

assign zext_ln1142_fu_582_p1 = iter_1_reg_1170_pp0_iter4_reg;

assign zext_ln15_1_fu_1032_p1 = mantissa_1_fu_1022_p4;

assign zext_ln15_2_fu_621_p1 = mantissa_2_fu_611_p4;

assign zext_ln15_3_fu_758_p1 = mantissa_3_fu_748_p4;

assign zext_ln15_fu_895_p1 = mantissa_fu_885_p4;

assign zext_ln18_1_fu_1076_p1 = $unsigned(sext_ln18_3_fu_1072_p1);

assign zext_ln18_2_fu_665_p1 = $unsigned(sext_ln18_5_fu_661_p1);

assign zext_ln18_3_fu_802_p1 = $unsigned(sext_ln18_7_fu_798_p1);

assign zext_ln18_fu_939_p1 = $unsigned(sext_ln18_1_fu_935_p1);

assign zext_ln486_1_fu_1036_p1 = xs_exp_1_fu_1010_p3;

assign zext_ln486_2_fu_625_p1 = xs_exp_2_fu_599_p3;

assign zext_ln486_3_fu_762_p1 = xs_exp_3_fu_736_p3;

assign zext_ln486_fu_899_p1 = xs_exp_fu_873_p3;

assign zext_ln882_cast_fu_279_p1 = zext_ln882;

endmodule //atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1114_37
