// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_load_target_geometry_Pipeline_VITIS_LOOP_42_1_VITIS_LOOP_44_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem4_0_AWVALID,
        m_axi_gmem4_0_AWREADY,
        m_axi_gmem4_0_AWADDR,
        m_axi_gmem4_0_AWID,
        m_axi_gmem4_0_AWLEN,
        m_axi_gmem4_0_AWSIZE,
        m_axi_gmem4_0_AWBURST,
        m_axi_gmem4_0_AWLOCK,
        m_axi_gmem4_0_AWCACHE,
        m_axi_gmem4_0_AWPROT,
        m_axi_gmem4_0_AWQOS,
        m_axi_gmem4_0_AWREGION,
        m_axi_gmem4_0_AWUSER,
        m_axi_gmem4_0_WVALID,
        m_axi_gmem4_0_WREADY,
        m_axi_gmem4_0_WDATA,
        m_axi_gmem4_0_WSTRB,
        m_axi_gmem4_0_WLAST,
        m_axi_gmem4_0_WID,
        m_axi_gmem4_0_WUSER,
        m_axi_gmem4_0_ARVALID,
        m_axi_gmem4_0_ARREADY,
        m_axi_gmem4_0_ARADDR,
        m_axi_gmem4_0_ARID,
        m_axi_gmem4_0_ARLEN,
        m_axi_gmem4_0_ARSIZE,
        m_axi_gmem4_0_ARBURST,
        m_axi_gmem4_0_ARLOCK,
        m_axi_gmem4_0_ARCACHE,
        m_axi_gmem4_0_ARPROT,
        m_axi_gmem4_0_ARQOS,
        m_axi_gmem4_0_ARREGION,
        m_axi_gmem4_0_ARUSER,
        m_axi_gmem4_0_RVALID,
        m_axi_gmem4_0_RREADY,
        m_axi_gmem4_0_RDATA,
        m_axi_gmem4_0_RLAST,
        m_axi_gmem4_0_RID,
        m_axi_gmem4_0_RFIFONUM,
        m_axi_gmem4_0_RUSER,
        m_axi_gmem4_0_RRESP,
        m_axi_gmem4_0_BVALID,
        m_axi_gmem4_0_BREADY,
        m_axi_gmem4_0_BRESP,
        m_axi_gmem4_0_BID,
        m_axi_gmem4_0_BUSER,
        targetGeometry_cols_write,
        bound,
        sext_ln0,
        targetGeometry_mem,
        targetGeometry_data_s_address1,
        targetGeometry_data_s_ce1,
        targetGeometry_data_s_we1,
        targetGeometry_data_s_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem4_0_AWVALID;
input   m_axi_gmem4_0_AWREADY;
output  [63:0] m_axi_gmem4_0_AWADDR;
output  [0:0] m_axi_gmem4_0_AWID;
output  [31:0] m_axi_gmem4_0_AWLEN;
output  [2:0] m_axi_gmem4_0_AWSIZE;
output  [1:0] m_axi_gmem4_0_AWBURST;
output  [1:0] m_axi_gmem4_0_AWLOCK;
output  [3:0] m_axi_gmem4_0_AWCACHE;
output  [2:0] m_axi_gmem4_0_AWPROT;
output  [3:0] m_axi_gmem4_0_AWQOS;
output  [3:0] m_axi_gmem4_0_AWREGION;
output  [0:0] m_axi_gmem4_0_AWUSER;
output   m_axi_gmem4_0_WVALID;
input   m_axi_gmem4_0_WREADY;
output  [7:0] m_axi_gmem4_0_WDATA;
output  [0:0] m_axi_gmem4_0_WSTRB;
output   m_axi_gmem4_0_WLAST;
output  [0:0] m_axi_gmem4_0_WID;
output  [0:0] m_axi_gmem4_0_WUSER;
output   m_axi_gmem4_0_ARVALID;
input   m_axi_gmem4_0_ARREADY;
output  [63:0] m_axi_gmem4_0_ARADDR;
output  [0:0] m_axi_gmem4_0_ARID;
output  [31:0] m_axi_gmem4_0_ARLEN;
output  [2:0] m_axi_gmem4_0_ARSIZE;
output  [1:0] m_axi_gmem4_0_ARBURST;
output  [1:0] m_axi_gmem4_0_ARLOCK;
output  [3:0] m_axi_gmem4_0_ARCACHE;
output  [2:0] m_axi_gmem4_0_ARPROT;
output  [3:0] m_axi_gmem4_0_ARQOS;
output  [3:0] m_axi_gmem4_0_ARREGION;
output  [0:0] m_axi_gmem4_0_ARUSER;
input   m_axi_gmem4_0_RVALID;
output   m_axi_gmem4_0_RREADY;
input  [7:0] m_axi_gmem4_0_RDATA;
input   m_axi_gmem4_0_RLAST;
input  [0:0] m_axi_gmem4_0_RID;
input  [10:0] m_axi_gmem4_0_RFIFONUM;
input  [0:0] m_axi_gmem4_0_RUSER;
input  [1:0] m_axi_gmem4_0_RRESP;
input   m_axi_gmem4_0_BVALID;
output   m_axi_gmem4_0_BREADY;
input  [1:0] m_axi_gmem4_0_BRESP;
input  [0:0] m_axi_gmem4_0_BID;
input  [0:0] m_axi_gmem4_0_BUSER;
input  [31:0] targetGeometry_cols_write;
input  [61:0] bound;
input  [31:0] sext_ln0;
input  [63:0] targetGeometry_mem;
output  [9:0] targetGeometry_data_s_address1;
output   targetGeometry_data_s_ce1;
output   targetGeometry_data_s_we1;
output  [0:0] targetGeometry_data_s_d1;

reg ap_idle;
reg m_axi_gmem4_0_ARVALID;
reg m_axi_gmem4_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln42_fu_165_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem4_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem4_blk_n_R;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire  signed [61:0] sext_ln0_cast_fu_143_p1;
reg  signed [61:0] sext_ln0_cast_reg_306;
reg   [0:0] icmp_ln42_reg_311;
wire   [63:0] zext_ln47_fu_233_p1;
reg   [63:0] zext_ln47_reg_315;
reg   [63:0] zext_ln47_reg_315_pp0_iter3_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter4_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter5_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter6_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter7_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter8_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter9_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter10_reg;
reg   [63:0] zext_ln47_reg_315_pp0_iter11_reg;
reg   [63:0] gmem4_addr_reg_320;
reg   [7:0] gmem4_addr_read_reg_326;
reg    ap_condition_exit_pp0_iter2_stage0;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] add_ln47_fu_237_p2;
reg   [30:0] col_fu_74;
wire   [30:0] add_ln44_fu_248_p2;
wire    ap_loop_init;
reg   [30:0] r_fu_78;
wire   [30:0] select_ln42_1_fu_210_p3;
reg   [61:0] indvar_flatten_fu_82;
wire   [61:0] add_ln42_1_fu_170_p2;
wire    ap_block_pp0_stage0;
reg    targetGeometry_data_s_we1_local;
wire   [0:0] icmp_ln47_fu_264_p2;
reg    targetGeometry_data_s_ce1_local;
wire  signed [31:0] empty_fu_139_p0;
wire   [30:0] empty_fu_139_p1;
wire   [31:0] zext_ln44_1_fu_184_p1;
wire   [0:0] icmp_ln44_fu_188_p2;
wire   [30:0] add_ln42_fu_196_p2;
wire   [30:0] select_ln42_fu_202_p3;
wire   [61:0] empty_fu_139_p2;
wire   [61:0] zext_ln44_fu_223_p1;
wire   [61:0] add_ln46_fu_227_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [61:0] empty_fu_139_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 col_fu_74 = 31'd0;
#0 r_fu_78 = 31'd0;
#0 indvar_flatten_fu_82 = 62'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_mul_32s_31ns_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_32s_31ns_62_1_1_U510(
    .din0(empty_fu_139_p0),
    .din1(empty_fu_139_p1),
    .dout(empty_fu_139_p2)
);

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            col_fu_74 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln42_reg_311 == 1'd0))) begin
            col_fu_74 <= add_ln44_fu_248_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 62'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_fu_165_p2 == 1'd0))) begin
            indvar_flatten_fu_82 <= add_ln42_1_fu_170_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            r_fu_78 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln42_reg_311 == 1'd0))) begin
            r_fu_78 <= select_ln42_1_fu_210_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln42_reg_311 <= icmp_ln42_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem4_addr_read_reg_326 <= m_axi_gmem4_0_RDATA;
        gmem4_addr_reg_320 <= add_ln47_fu_237_p2;
        zext_ln47_reg_315[61 : 0] <= zext_ln47_fu_233_p1[61 : 0];
        zext_ln47_reg_315_pp0_iter10_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter9_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter11_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter10_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter3_reg[61 : 0] <= zext_ln47_reg_315[61 : 0];
        zext_ln47_reg_315_pp0_iter4_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter3_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter5_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter4_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter6_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter5_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter7_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter6_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter8_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter7_reg[61 : 0];
        zext_ln47_reg_315_pp0_iter9_reg[61 : 0] <= zext_ln47_reg_315_pp0_iter8_reg[61 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        sext_ln0_cast_reg_306 <= sext_ln0_cast_fu_143_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln42_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln42_reg_311 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem4_blk_n_AR = m_axi_gmem4_0_ARREADY;
    end else begin
        gmem4_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem4_blk_n_R = m_axi_gmem4_0_RVALID;
    end else begin
        gmem4_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem4_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem4_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem4_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem4_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        targetGeometry_data_s_ce1_local = 1'b1;
    end else begin
        targetGeometry_data_s_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        targetGeometry_data_s_we1_local = 1'b1;
    end else begin
        targetGeometry_data_s_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_1_fu_170_p2 = (indvar_flatten_fu_82 + 62'd1);

assign add_ln42_fu_196_p2 = (r_fu_78 + 31'd1);

assign add_ln44_fu_248_p2 = (select_ln42_fu_202_p3 + 31'd1);

assign add_ln46_fu_227_p2 = (empty_fu_139_p2 + zext_ln44_fu_223_p1);

assign add_ln47_fu_237_p2 = (zext_ln47_fu_233_p1 + targetGeometry_mem);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem4_0_RVALID == 1'b0)) | ((m_axi_gmem4_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem4_0_RVALID == 1'b0)) | ((m_axi_gmem4_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem4_0_RVALID == 1'b0)) | ((m_axi_gmem4_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_139_p0 = sext_ln0_cast_reg_306;

assign empty_fu_139_p1 = empty_fu_139_p10;

assign empty_fu_139_p10 = select_ln42_1_fu_210_p3;

assign icmp_ln42_fu_165_p2 = ((indvar_flatten_fu_82 == bound) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_188_p2 = (($signed(zext_ln44_1_fu_184_p1) < $signed(targetGeometry_cols_write)) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_264_p2 = ((gmem4_addr_read_reg_326 != 8'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem4_0_ARADDR = gmem4_addr_reg_320;

assign m_axi_gmem4_0_ARBURST = 2'd0;

assign m_axi_gmem4_0_ARCACHE = 4'd0;

assign m_axi_gmem4_0_ARID = 1'd0;

assign m_axi_gmem4_0_ARLEN = 64'd1;

assign m_axi_gmem4_0_ARLOCK = 2'd0;

assign m_axi_gmem4_0_ARPROT = 3'd0;

assign m_axi_gmem4_0_ARQOS = 4'd0;

assign m_axi_gmem4_0_ARREGION = 4'd0;

assign m_axi_gmem4_0_ARSIZE = 3'd0;

assign m_axi_gmem4_0_ARUSER = 1'd0;

assign m_axi_gmem4_0_AWADDR = 64'd0;

assign m_axi_gmem4_0_AWBURST = 2'd0;

assign m_axi_gmem4_0_AWCACHE = 4'd0;

assign m_axi_gmem4_0_AWID = 1'd0;

assign m_axi_gmem4_0_AWLEN = 32'd0;

assign m_axi_gmem4_0_AWLOCK = 2'd0;

assign m_axi_gmem4_0_AWPROT = 3'd0;

assign m_axi_gmem4_0_AWQOS = 4'd0;

assign m_axi_gmem4_0_AWREGION = 4'd0;

assign m_axi_gmem4_0_AWSIZE = 3'd0;

assign m_axi_gmem4_0_AWUSER = 1'd0;

assign m_axi_gmem4_0_AWVALID = 1'b0;

assign m_axi_gmem4_0_BREADY = 1'b0;

assign m_axi_gmem4_0_WDATA = 8'd0;

assign m_axi_gmem4_0_WID = 1'd0;

assign m_axi_gmem4_0_WLAST = 1'b0;

assign m_axi_gmem4_0_WSTRB = 1'd0;

assign m_axi_gmem4_0_WUSER = 1'd0;

assign m_axi_gmem4_0_WVALID = 1'b0;

assign select_ln42_1_fu_210_p3 = ((icmp_ln44_fu_188_p2[0:0] == 1'b1) ? r_fu_78 : add_ln42_fu_196_p2);

assign select_ln42_fu_202_p3 = ((icmp_ln44_fu_188_p2[0:0] == 1'b1) ? col_fu_74 : 31'd0);

assign sext_ln0_cast_fu_143_p1 = $signed(sext_ln0);

assign targetGeometry_data_s_address1 = zext_ln47_reg_315_pp0_iter11_reg;

assign targetGeometry_data_s_ce1 = targetGeometry_data_s_ce1_local;

assign targetGeometry_data_s_d1 = icmp_ln47_fu_264_p2;

assign targetGeometry_data_s_we1 = targetGeometry_data_s_we1_local;

assign zext_ln44_1_fu_184_p1 = col_fu_74;

assign zext_ln44_fu_223_p1 = select_ln42_fu_202_p3;

assign zext_ln47_fu_233_p1 = add_ln46_fu_227_p2;

always @ (posedge ap_clk) begin
    zext_ln47_reg_315[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter3_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter4_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter5_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter6_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter7_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter8_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter9_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter10_reg[63:62] <= 2'b00;
    zext_ln47_reg_315_pp0_iter11_reg[63:62] <= 2'b00;
end

endmodule //atomflow_controller_load_target_geometry_Pipeline_VITIS_LOOP_42_1_VITIS_LOOP_44_2
