// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1695_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        end_colSelectionCount,
        sub175,
        empty,
        usableAtoms_data_address0,
        usableAtoms_data_ce0,
        usableAtoms_data_q0,
        start_colSelection_address0,
        start_colSelection_ce0,
        start_colSelection_we0,
        start_colSelection_d0,
        sub186,
        zext_ln1706_1,
        targetSites_data_address0,
        targetSites_data_ce0,
        targetSites_data_q0,
        end_colSelection_address0,
        end_colSelection_ce0,
        end_colSelection_we0,
        end_colSelection_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] end_colSelectionCount;
input  [15:0] sub175;
input  [15:0] empty;
output  [15:0] usableAtoms_data_address0;
output   usableAtoms_data_ce0;
input  [31:0] usableAtoms_data_q0;
output  [3:0] start_colSelection_address0;
output   start_colSelection_ce0;
output   start_colSelection_we0;
output  [15:0] start_colSelection_d0;
input  [15:0] sub186;
input  [15:0] zext_ln1706_1;
output  [15:0] targetSites_data_address0;
output   targetSites_data_ce0;
input  [7:0] targetSites_data_q0;
output  [3:0] end_colSelection_address0;
output   end_colSelection_ce0;
output   end_colSelection_we0;
output  [7:0] end_colSelection_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1695_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
reg   [4:0] i_94_reg_225;
wire   [63:0] zext_ln1704_fu_181_p1;
wire   [63:0] zext_ln1706_fu_198_p1;
wire   [63:0] zext_ln1703_fu_213_p1;
reg   [4:0] i_fu_58;
wire   [4:0] start_colSelectionCount_fu_159_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_94;
reg    usableAtoms_data_ce0_local;
reg    targetSites_data_ce0_local;
reg    start_colSelection_we0_local;
wire   [15:0] trunc_ln1704_fu_208_p1;
reg    start_colSelection_ce0_local;
reg    end_colSelection_we0_local;
reg    end_colSelection_ce0_local;
wire   [15:0] zext_ln1695_fu_165_p1;
wire   [15:0] sub_ln1704_fu_169_p2;
wire   [15:0] add_ln1704_fu_175_p2;
wire   [15:0] sub_ln1706_fu_186_p2;
wire   [15:0] add_ln1706_fu_192_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 i_fu_58 = 5'd0;
#0 ap_done_reg = 1'b0;
end

atomflow_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln1695_fu_153_p2 == 1'd0)) begin
            i_fu_58 <= start_colSelectionCount_fu_159_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_94_reg_225 <= ap_sig_allocacmp_i_94;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1695_fu_153_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_94 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_94 = i_fu_58;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        end_colSelection_ce0_local = 1'b1;
    end else begin
        end_colSelection_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        end_colSelection_we0_local = 1'b1;
    end else begin
        end_colSelection_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        start_colSelection_ce0_local = 1'b1;
    end else begin
        start_colSelection_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        start_colSelection_we0_local = 1'b1;
    end else begin
        start_colSelection_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        targetSites_data_ce0_local = 1'b1;
    end else begin
        targetSites_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        usableAtoms_data_ce0_local = 1'b1;
    end else begin
        usableAtoms_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1695_fu_153_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1704_fu_175_p2 = (empty + sub_ln1704_fu_169_p2);

assign add_ln1706_fu_192_p2 = (zext_ln1706_1 + sub_ln1706_fu_186_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign end_colSelection_address0 = zext_ln1703_fu_213_p1;

assign end_colSelection_ce0 = end_colSelection_ce0_local;

assign end_colSelection_d0 = targetSites_data_q0;

assign end_colSelection_we0 = end_colSelection_we0_local;

assign icmp_ln1695_fu_153_p2 = ((ap_sig_allocacmp_i_94 == end_colSelectionCount) ? 1'b1 : 1'b0);

assign start_colSelectionCount_fu_159_p2 = (ap_sig_allocacmp_i_94 + 5'd1);

assign start_colSelection_address0 = zext_ln1703_fu_213_p1;

assign start_colSelection_ce0 = start_colSelection_ce0_local;

assign start_colSelection_d0 = trunc_ln1704_fu_208_p1;

assign start_colSelection_we0 = start_colSelection_we0_local;

assign sub_ln1704_fu_169_p2 = (sub175 - zext_ln1695_fu_165_p1);

assign sub_ln1706_fu_186_p2 = (sub186 - zext_ln1695_fu_165_p1);

assign targetSites_data_address0 = zext_ln1706_fu_198_p1;

assign targetSites_data_ce0 = targetSites_data_ce0_local;

assign trunc_ln1704_fu_208_p1 = usableAtoms_data_q0[15:0];

assign usableAtoms_data_address0 = zext_ln1704_fu_181_p1;

assign usableAtoms_data_ce0 = usableAtoms_data_ce0_local;

assign zext_ln1695_fu_165_p1 = ap_sig_allocacmp_i_94;

assign zext_ln1703_fu_213_p1 = i_94_reg_225;

assign zext_ln1704_fu_181_p1 = add_ln1704_fu_175_p2;

assign zext_ln1706_fu_198_p1 = add_ln1706_fu_192_p2;

endmodule //atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1695_7
