// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module atomflow_controller_execute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        move_address0,
        move_ce0,
        move_q0,
        move_address1,
        move_ce1,
        move_q1,
        stateArray_data_s_address1,
        stateArray_data_s_ce1,
        stateArray_data_s_we1,
        stateArray_data_s_d1,
        stateArray_rows_val,
        stateArray_cols_val
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_pp0_stage0 = 20'd4096;
parameter    ap_ST_fsm_pp0_stage1 = 20'd8192;
parameter    ap_ST_fsm_state19 = 20'd16384;
parameter    ap_ST_fsm_pp1_stage0 = 20'd32768;
parameter    ap_ST_fsm_pp1_stage1 = 20'd65536;
parameter    ap_ST_fsm_pp1_stage2 = 20'd131072;
parameter    ap_ST_fsm_pp1_stage3 = 20'd262144;
parameter    ap_ST_fsm_state27 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] move_address0;
output   move_ce0;
input  [15:0] move_q0;
output  [9:0] move_address1;
output   move_ce1;
input  [15:0] move_q1;
output  [9:0] stateArray_data_s_address1;
output   stateArray_data_s_ce1;
output   stateArray_data_s_we1;
output  [0:0] stateArray_data_s_d1;
input  [15:0] stateArray_rows_val;
input  [15:0] stateArray_cols_val;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] move_address0;
reg move_ce0;
reg[9:0] move_address1;
reg move_ce1;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire  signed [9:0] empty_fu_322_p1;
reg  signed [9:0] empty_reg_1126;
wire   [7:0] trunc_ln2107_fu_326_p1;
reg   [7:0] trunc_ln2107_reg_1132;
wire   [0:0] icmp_ln2107_fu_330_p2;
reg   [0:0] icmp_ln2107_reg_1137;
wire   [10:0] add_ln2114_1_fu_366_p2;
reg   [10:0] add_ln2114_1_reg_1146;
wire   [7:0] trunc_ln2114_fu_393_p1;
reg   [7:0] trunc_ln2114_reg_1158;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln2114_fu_401_p2;
reg   [0:0] icmp_ln2114_reg_1166;
wire   [7:0] grp_fu_312_p4;
reg   [7:0] trunc_ln_reg_1170;
wire   [0:0] icmp_ln2115_fu_427_p2;
reg   [0:0] icmp_ln2115_reg_1182;
wire    ap_CS_fsm_state4;
wire   [0:0] or_ln2119_fu_442_p2;
reg   [0:0] or_ln2119_reg_1186;
wire   [0:0] icmp_ln2126_fu_456_p2;
reg   [0:0] icmp_ln2126_reg_1197;
wire    ap_CS_fsm_state5;
wire   [4:0] stepIdx_2_fu_462_p2;
reg   [4:0] stepIdx_2_reg_1201;
wire   [0:0] icmp_ln2131_fu_472_p2;
reg   [0:0] icmp_ln2131_reg_1206;
wire   [10:0] mul_ln_fu_477_p4;
reg   [10:0] mul_ln_reg_1210;
wire   [15:0] rowMax_fu_508_p2;
reg   [15:0] rowMax_reg_1243;
wire   [15:0] colMax_fu_513_p2;
reg   [15:0] colMax_reg_1250;
wire   [15:0] mul_ln2151_fu_524_p2;
reg   [15:0] mul_ln2151_reg_1257;
reg   [7:0] count_assign_reg_1263;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln2136_fu_565_p2;
reg   [0:0] icmp_ln2136_reg_1268;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_return;
reg   [0:0] targetBlock_reg_1272;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [7:0] trunc_ln2143_fu_591_p1;
reg   [7:0] trunc_ln2143_reg_1281;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln2143_fu_605_p2;
reg   [0:0] icmp_ln2143_reg_1286;
wire   [0:0] icmp_ln2156_fu_618_p2;
reg   [0:0] icmp_ln2156_reg_1293;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln2156_fu_646_p3;
reg   [7:0] select_ln2156_reg_1297;
wire  signed [9:0] trunc_ln2162_fu_716_p1;
reg  signed [9:0] trunc_ln2162_reg_1307;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] and_ln2170_fu_749_p2;
reg   [0:0] and_ln2170_reg_1312;
reg   [0:0] and_ln2170_reg_1312_pp0_iter1_reg;
wire   [0:0] and_ln2172_fu_780_p2;
reg   [0:0] and_ln2172_reg_1321;
reg   [0:0] and_ln2172_reg_1321_pp0_iter2_reg;
wire   [9:0] trunc_ln0_fu_786_p1;
reg   [9:0] trunc_ln0_reg_1325;
wire   [0:0] icmp_ln2183_fu_812_p2;
reg   [0:0] icmp_ln2183_reg_1351;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_pp1_stage0_11001;
wire   [7:0] select_ln2183_fu_840_p3;
reg   [7:0] select_ln2183_reg_1355;
reg   [15:0] row_1_reg_1371;
wire    ap_CS_fsm_pp1_stage1;
reg    ap_enable_reg_pp1_iter0;
reg    ap_enable_reg_pp1_iter0_reg;
wire    ap_block_pp1_stage1_11001;
wire  signed [9:0] trunc_ln2189_fu_934_p1;
reg  signed [9:0] trunc_ln2189_reg_1378;
wire   [0:0] and_ln2198_fu_967_p2;
reg   [0:0] and_ln2198_reg_1383;
wire   [0:0] and_ln2200_fu_998_p2;
reg   [0:0] and_ln2200_reg_1392;
wire    ap_CS_fsm_pp1_stage2;
wire    ap_block_pp1_stage2_11001;
wire   [0:0] destRowValid_fu_1004_p2;
reg   [0:0] destRowValid_reg_1396;
wire   [0:0] icmp_ln2206_fu_1040_p2;
reg   [0:0] icmp_ln2206_reg_1405;
wire   [0:0] and_ln2206_1_fu_1072_p2;
reg   [0:0] and_ln2206_1_reg_1410;
wire    ap_CS_fsm_pp1_stage3;
wire    ap_block_pp1_stage3_11001;
reg   [0:0] tmp_559_reg_1414;
wire   [9:0] trunc_ln0_1_fu_1091_p1;
reg   [9:0] trunc_ln0_1_reg_1418;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state13;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter2;
wire    ap_CS_fsm_state19;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state20;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage3_subdone;
wire    ap_block_pp1_stage2_subdone;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_done;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_idle;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_ready;
wire   [9:0] grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address0;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce0;
wire   [9:0] grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address1;
wire    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce1;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_done;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_idle;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_ready;
wire   [9:0] grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address0;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce0;
wire   [9:0] grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address1;
wire    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce1;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return;
reg    grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln2114_fu_388_p1;
wire   [63:0] zext_ln2115_fu_422_p1;
wire   [63:0] zext_ln2136_fu_503_p1;
wire   [63:0] zext_ln2143_fu_586_p1;
wire   [63:0] p_cast5_fu_690_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln2162_fu_720_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln316_fu_790_p1;
wire   [63:0] p_cast6_fu_893_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] p_cast4_cast_fu_908_p1;
wire   [63:0] zext_ln2189_fu_938_p1;
wire    ap_block_pp1_stage1;
wire   [63:0] zext_ln2205_fu_1035_p1;
wire    ap_block_pp1_stage2;
wire   [63:0] zext_ln316_2_fu_1095_p1;
reg    ap_predicate_pred484_state26;
reg   [4:0] stepIdx_fu_122;
reg    ap_predicate_op122_call_state12;
reg    ap_block_state12_on_subcall_done;
reg   [7:0] colTone_fu_126;
wire   [7:0] colTone_2_fu_695_p2;
reg   [7:0] rowTone_fu_130;
wire   [7:0] select_ln2156_1_fu_654_p3;
reg   [15:0] indvar_flatten_fu_134;
wire   [15:0] add_ln2156_fu_623_p2;
reg   [7:0] colTone_1_fu_138;
wire   [7:0] colTone_3_fu_913_p2;
reg   [7:0] rowTone_1_fu_142;
wire   [7:0] select_ln2183_1_fu_848_p3;
reg   [15:0] indvar_flatten6_fu_146;
wire   [15:0] add_ln2183_fu_817_p2;
reg    move_ce0_local;
reg   [9:0] move_address0_local;
reg    move_ce1_local;
reg   [9:0] move_address1_local;
reg    stateArray_data_s_we1_local;
reg   [0:0] stateArray_data_s_d1_local;
reg    stateArray_data_s_ce1_local;
reg   [9:0] stateArray_data_s_address1_local;
wire   [7:0] add_ln2112_fu_336_p2;
wire   [4:0] trunc_ln2114_1_fu_342_p1;
wire   [8:0] tmp_552_fu_354_p3;
wire   [10:0] p_shl_fu_346_p3;
wire   [10:0] zext_ln2114_1_fu_362_p1;
wire   [10:0] add_ln2114_fu_372_p2;
wire   [9:0] lshr_ln_fu_378_p4;
wire   [7:0] trunc_ln2114_2_fu_397_p1;
wire   [10:0] add_ln2115_fu_407_p2;
wire   [9:0] lshr_ln2115_2_fu_412_p4;
wire   [0:0] icmp_ln2119_fu_432_p2;
wire   [0:0] icmp_ln2119_1_fu_437_p2;
wire   [7:0] zext_ln2126_fu_468_p1;
wire   [10:0] add_ln2136_fu_487_p2;
wire   [9:0] lshr_ln3_fu_493_p4;
wire   [7:0] mul_ln2151_fu_524_p0;
wire   [7:0] mul_ln2151_fu_524_p1;
wire   [6:0] tmp_553_fu_555_p4;
wire   [10:0] add_ln2143_fu_571_p2;
wire   [9:0] lshr_ln4_fu_576_p4;
wire   [6:0] tmp_555_fu_595_p4;
wire   [0:0] icmp_ln2162_fu_641_p2;
wire   [7:0] rowTone_3_fu_635_p2;
wire   [8:0] tmp_fu_662_p3;
wire   [9:0] p_cast_fu_670_p1;
wire   [9:0] empty_179_fu_674_p2;
wire   [8:0] tmp_s_fu_680_p4;
wire   [0:0] tmp_554_fu_724_p3;
wire   [0:0] icmp_ln2171_fu_738_p2;
wire   [0:0] xor_ln2171_fu_743_p2;
wire   [0:0] xor_ln2170_fu_732_p2;
wire   [0:0] tmp_556_fu_755_p3;
wire   [0:0] icmp_ln2173_fu_769_p2;
wire   [0:0] xor_ln2173_fu_774_p2;
wire   [0:0] xor_ln2172_fu_763_p2;
wire  signed [9:0] zext_ln316_fu_790_p0;
wire   [9:0] grp_fu_1099_p3;
wire   [0:0] icmp_ln2189_fu_835_p2;
wire   [7:0] rowTone_5_fu_829_p2;
wire   [8:0] tmp_525_fu_856_p3;
wire   [9:0] p_cast7_fu_864_p1;
wire   [9:0] empty_180_fu_868_p2;
wire   [10:0] tmp3_cast_fu_874_p1;
wire   [8:0] tmp_526_fu_883_p4;
wire   [10:0] empty_181_fu_878_p2;
wire   [9:0] tmp_527_fu_898_p4;
wire   [0:0] tmp_557_fu_942_p3;
wire   [0:0] icmp_ln2199_fu_956_p2;
wire   [0:0] xor_ln2199_fu_961_p2;
wire   [0:0] xor_ln2198_fu_950_p2;
wire   [0:0] tmp_558_fu_973_p3;
wire   [0:0] icmp_ln2201_fu_987_p2;
wire   [0:0] xor_ln2201_fu_992_p2;
wire   [0:0] xor_ln2200_fu_981_p2;
wire   [8:0] shl_ln1_fu_1009_p3;
wire   [10:0] zext_ln2205_1_fu_1016_p1;
wire   [10:0] add_ln2205_fu_1020_p2;
wire   [9:0] lshr_ln5_fu_1025_p4;
wire    ap_block_pp1_stage3;
wire   [0:0] icmp_ln2207_fu_1055_p2;
wire   [0:0] xor_ln2206_fu_1050_p2;
wire   [0:0] xor_ln2207_fu_1060_p2;
wire   [0:0] and_ln2206_fu_1066_p2;
wire   [0:0] destColValid_fu_1044_p2;
wire   [15:0] or_ln2214_fu_1078_p2;
wire  signed [9:0] zext_ln316_2_fu_1095_p0;
wire   [9:0] grp_fu_1105_p3;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_block_state8_on_subcall_done;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_block_pp1_stage1_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [15:0] mul_ln2151_fu_524_p00;
wire   [15:0] mul_ln2151_fu_524_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg = 1'b0;
#0 grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg = 1'b0;
#0 stepIdx_fu_122 = 5'd0;
#0 colTone_fu_126 = 8'd0;
#0 rowTone_fu_130 = 8'd0;
#0 indvar_flatten_fu_134 = 16'd0;
#0 colTone_1_fu_138 = 8'd0;
#0 rowTone_1_fu_142 = 8'd0;
#0 indvar_flatten6_fu_146 = 16'd0;
end

atomflow_controller_execute_Pipeline_VITIS_LOOP_106_1 grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start),
    .ap_done(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_done),
    .ap_idle(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_idle),
    .ap_ready(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_ready),
    .count_assign(count_assign_reg_1263),
    .mul_ln2136(mul_ln_reg_1210),
    .move_address0(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address0),
    .move_ce0(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce0),
    .move_q0(move_q0),
    .move_address1(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address1),
    .move_ce1(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce1),
    .move_q1(move_q1),
    .ap_return(grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_return)
);

atomflow_controller_execute_Pipeline_VITIS_LOOP_106_16 grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start),
    .ap_done(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_done),
    .ap_idle(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_idle),
    .ap_ready(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_ready),
    .empty(trunc_ln2143_reg_1281),
    .mul_ln2136(mul_ln_reg_1210),
    .move_address0(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address0),
    .move_ce0(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce0),
    .move_q0(move_q0),
    .move_address1(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address1),
    .move_ce1(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce1),
    .move_q1(move_q1),
    .ap_return(grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return)
);

atomflow_controller_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U642(
    .din0(mul_ln2151_fu_524_p0),
    .din1(mul_ln2151_fu_524_p1),
    .dout(mul_ln2151_fu_524_p2)
);

atomflow_controller_mac_muladd_10s_10s_10ns_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mac_muladd_10s_10s_10ns_10_4_1_U643(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln2162_reg_1307),
    .din1(empty_reg_1126),
    .din2(trunc_ln0_reg_1325),
    .ce(1'b1),
    .dout(grp_fu_1099_p3)
);

atomflow_controller_mac_muladd_10s_10s_10ns_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mac_muladd_10s_10s_10ns_10_4_1_U644(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln2189_reg_1378),
    .din1(empty_reg_1126),
    .din2(trunc_ln0_1_reg_1418),
    .ce(1'b1),
    .dout(grp_fu_1105_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state13) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state13) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp1_iter0_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_subdone)) | ((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_subdone)))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg <= 1'b1;
        end else if ((grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_ready == 1'b1)) begin
            grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg <= 1'b1;
        end else if ((grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_ready == 1'b1)) begin
            grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        colTone_1_fu_138 <= 8'd0;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln2183_fu_812_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        colTone_1_fu_138 <= colTone_3_fu_913_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
        colTone_fu_126 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln2156_fu_618_p2 == 1'd0))) begin
        colTone_fu_126 <= colTone_2_fu_695_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        indvar_flatten6_fu_146 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln2183_fu_812_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indvar_flatten6_fu_146 <= add_ln2183_fu_817_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
        indvar_flatten_fu_134 <= 16'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln2156_fu_618_p2 == 1'd0))) begin
        indvar_flatten_fu_134 <= add_ln2156_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        rowTone_1_fu_142 <= 8'd0;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln2183_fu_812_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        rowTone_1_fu_142 <= select_ln2183_1_fu_848_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
        rowTone_fu_130 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln2156_fu_618_p2 == 1'd0))) begin
        rowTone_fu_130 <= select_ln2156_1_fu_654_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2115_fu_427_p2 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (or_ln2119_fu_442_p2 == 1'd0))) begin
        stepIdx_fu_122 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12_on_subcall_done) & (((((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd1) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd1) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd1) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 
    == 1'd0) & (icmp_ln2143_reg_1286 == 1'd1) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
        stepIdx_fu_122 <= stepIdx_2_reg_1201;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln2114_1_reg_1146[10 : 1] <= add_ln2114_1_fu_366_p2[10 : 1];
        empty_reg_1126 <= empty_fu_322_p1;
        icmp_ln2107_reg_1137 <= icmp_ln2107_fu_330_p2;
        trunc_ln2107_reg_1132 <= trunc_ln2107_fu_326_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        and_ln2170_reg_1312 <= and_ln2170_fu_749_p2;
        and_ln2170_reg_1312_pp0_iter1_reg <= and_ln2170_reg_1312;
        trunc_ln2162_reg_1307 <= trunc_ln2162_fu_716_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln2172_reg_1321 <= and_ln2172_fu_780_p2;
        and_ln2172_reg_1321_pp0_iter2_reg <= and_ln2172_reg_1321;
        icmp_ln2156_reg_1293 <= icmp_ln2156_fu_618_p2;
        select_ln2156_reg_1297 <= select_ln2156_fu_646_p3;
        trunc_ln0_reg_1325 <= trunc_ln0_fu_786_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        and_ln2198_reg_1383 <= and_ln2198_fu_967_p2;
        ap_predicate_pred484_state26 <= ((1'd1 == and_ln2206_1_reg_1410) & (1'd1 == and_ln2200_reg_1392) & (1'd1 == and_ln2198_reg_1383) & (tmp_559_reg_1414 == 1'd0) & (destRowValid_reg_1396 == 1'd1));
        trunc_ln2189_reg_1378 <= trunc_ln2189_fu_934_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001))) begin
        and_ln2200_reg_1392 <= and_ln2200_fu_998_p2;
        destRowValid_reg_1396 <= destRowValid_fu_1004_p2;
        icmp_ln2206_reg_1405 <= icmp_ln2206_fu_1040_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001))) begin
        and_ln2206_1_reg_1410 <= and_ln2206_1_fu_1072_p2;
        tmp_559_reg_1414 <= or_ln2214_fu_1078_p2[32'd15];
        trunc_ln0_1_reg_1418 <= trunc_ln0_1_fu_1091_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        colMax_reg_1250 <= colMax_fu_513_p2;
        icmp_ln2126_reg_1197 <= icmp_ln2126_fu_456_p2;
        icmp_ln2131_reg_1206 <= icmp_ln2131_fu_472_p2;
        mul_ln2151_reg_1257 <= mul_ln2151_fu_524_p2;
        mul_ln_reg_1210[10 : 1] <= mul_ln_fu_477_p4[10 : 1];
        rowMax_reg_1243 <= rowMax_fu_508_p2;
        stepIdx_2_reg_1201 <= stepIdx_2_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        count_assign_reg_1263 <= {{move_q0[15:8]}};
        icmp_ln2136_reg_1268 <= icmp_ln2136_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln2114_reg_1166 <= icmp_ln2114_fu_401_p2;
        trunc_ln2114_reg_1158 <= trunc_ln2114_fu_393_p1;
        trunc_ln_reg_1170 <= {{move_q1[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln2115_reg_1182 <= icmp_ln2115_fu_427_p2;
        or_ln2119_reg_1186 <= or_ln2119_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        icmp_ln2143_reg_1286 <= icmp_ln2143_fu_605_p2;
        trunc_ln2143_reg_1281 <= trunc_ln2143_fu_591_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln2183_reg_1351 <= icmp_ln2183_fu_812_p2;
        select_ln2183_reg_1355 <= select_ln2183_fu_840_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        row_1_reg_1371 <= move_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        targetBlock_reg_1272 <= grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state12_on_subcall_done)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln2156_fu_618_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state13 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state13 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln2183_fu_812_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12_on_subcall_done) & ((icmp_ln2107_reg_1137 == 1'd1) | ((icmp_ln2114_reg_1166 == 1'd0) | ((icmp_ln2115_reg_1182 == 1'd0) | ((or_ln2119_reg_1186 == 1'd1) | ((icmp_ln2126_reg_1197 == 1'd0) | ((icmp_ln2131_reg_1206 == 1'd0) | (((targetBlock_reg_1272 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd0)) | ((grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0)))))))))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12_on_subcall_done) & ((icmp_ln2107_reg_1137 == 1'd1) | ((icmp_ln2114_reg_1166 == 1'd0) | ((icmp_ln2115_reg_1182 == 1'd0) | ((or_ln2119_reg_1186 == 1'd1) | ((icmp_ln2126_reg_1197 == 1'd0) | ((icmp_ln2131_reg_1206 == 1'd0) | (((targetBlock_reg_1272 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd0)) | ((grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0))))))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
        move_address0 = grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln2136_reg_1268 == 1'd0))) begin
        move_address0 = grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address0;
    end else begin
        move_address0 = move_address0_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1))) begin
        move_address0_local = zext_ln2189_fu_938_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        move_address0_local = p_cast4_cast_fu_908_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        move_address0_local = p_cast5_fu_690_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        move_address0_local = zext_ln2136_fu_503_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        move_address0_local = zext_ln2114_fu_388_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        move_address0_local = 64'd660;
    end else begin
        move_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
        move_address1 = grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_address1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln2136_reg_1268 == 1'd0))) begin
        move_address1 = grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_address1;
    end else begin
        move_address1 = move_address1_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2))) begin
        move_address1_local = zext_ln2205_fu_1035_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        move_address1_local = p_cast6_fu_893_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        move_address1_local = zext_ln2162_fu_720_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        move_address1_local = zext_ln2143_fu_586_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        move_address1_local = zext_ln2115_fu_422_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        move_address1_local = 64'd32;
    end else begin
        move_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
        move_ce0 = grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln2136_reg_1268 == 1'd0))) begin
        move_ce0 = grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce0;
    end else begin
        move_ce0 = move_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        move_ce0_local = 1'b1;
    end else begin
        move_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
        move_ce1 = grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_move_ce1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln2136_reg_1268 == 1'd0))) begin
        move_ce1 = grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_move_ce1;
    end else begin
        move_ce1 = move_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp1_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001)))) begin
        move_ce1_local = 1'b1;
    end else begin
        move_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2))) begin
        stateArray_data_s_address1_local = zext_ln316_2_fu_1095_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        stateArray_data_s_address1_local = zext_ln316_fu_790_p1;
    end else begin
        stateArray_data_s_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        stateArray_data_s_ce1_local = 1'b1;
    end else begin
        stateArray_data_s_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2))) begin
        stateArray_data_s_d1_local = 1'd1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        stateArray_data_s_d1_local = 1'd0;
    end else begin
        stateArray_data_s_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred484_state26 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'd1 == and_ln2172_reg_1321_pp0_iter2_reg) & (1'd1 == and_ln2170_reg_1312_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        stateArray_data_s_we1_local = 1'b1;
    end else begin
        stateArray_data_s_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln2107_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln2115_fu_427_p2 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (or_ln2119_fu_442_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln2131_fu_472_p2 == 1'd0) | (icmp_ln2126_fu_456_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln2136_fu_565_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == ap_block_state8_on_subcall_done) & (grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_return == 1'd0) & (icmp_ln2136_reg_1268 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == ap_block_state8_on_subcall_done) & ((grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_return == 1'd1) | (icmp_ln2136_reg_1268 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln2143_fu_605_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12_on_subcall_done) & ((icmp_ln2107_reg_1137 == 1'd1) | ((icmp_ln2114_reg_1166 == 1'd0) | ((icmp_ln2115_reg_1182 == 1'd0) | ((or_ln2119_reg_1186 == 1'd1) | ((icmp_ln2126_reg_1197 == 1'd0) | ((icmp_ln2131_reg_1206 == 1'd0) | (((targetBlock_reg_1272 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd0)) | ((grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12_on_subcall_done) & (((((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd1) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd1) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_return == 1'd1) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 
    == 1'd0) & (icmp_ln2143_reg_1286 == 1'd1) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln2156_fu_618_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln2156_fu_618_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln2183_fu_812_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln2183_fu_812_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_subdone)) & (1'b0 == ap_block_pp1_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((1'b0 == ap_block_pp1_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2112_fu_336_p2 = ($signed(trunc_ln2107_fu_326_p1) + $signed(8'd255));

assign add_ln2114_1_fu_366_p2 = (p_shl_fu_346_p3 + zext_ln2114_1_fu_362_p1);

assign add_ln2114_fu_372_p2 = (add_ln2114_1_fu_366_p2 + 11'd64);

assign add_ln2115_fu_407_p2 = (add_ln2114_1_reg_1146 + 11'd65);

assign add_ln2136_fu_487_p2 = (mul_ln_fu_477_p4 + 11'd65);

assign add_ln2143_fu_571_p2 = (mul_ln_reg_1210 + 11'd64);

assign add_ln2156_fu_623_p2 = (indvar_flatten_fu_134 + 16'd1);

assign add_ln2183_fu_817_p2 = (indvar_flatten6_fu_146 + 16'd1);

assign add_ln2205_fu_1020_p2 = (add_ln2114_1_reg_1146 + zext_ln2205_1_fu_1016_p1);

assign and_ln2170_fu_749_p2 = (xor_ln2171_fu_743_p2 & xor_ln2170_fu_732_p2);

assign and_ln2172_fu_780_p2 = (xor_ln2173_fu_774_p2 & xor_ln2172_fu_763_p2);

assign and_ln2198_fu_967_p2 = (xor_ln2199_fu_961_p2 & xor_ln2198_fu_950_p2);

assign and_ln2200_fu_998_p2 = (xor_ln2201_fu_992_p2 & xor_ln2200_fu_981_p2);

assign and_ln2206_1_fu_1072_p2 = (destColValid_fu_1044_p2 & and_ln2206_fu_1066_p2);

assign and_ln2206_fu_1066_p2 = (xor_ln2207_fu_1060_p2 & xor_ln2206_fu_1050_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp1_stage3 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_on_subcall_done = ((ap_predicate_op122_call_state12 == 1'b1) & (grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_done == 1'b0) & (icmp_ln2136_reg_1268 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_predicate_op122_call_state12 = (((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (icmp_ln2136_reg_1268 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)) | ((icmp_ln2115_reg_1182 == 1'd1) & (icmp_ln2114_reg_1166 == 1'd1) & (icmp_ln2107_reg_1137 == 1'd0) & (icmp_ln2143_reg_1286 == 1'd0) & (targetBlock_reg_1272 == 1'd1) & (icmp_ln2131_reg_1206 == 1'd1) & (icmp_ln2126_reg_1197 == 1'd1) & (or_ln2119_reg_1186 == 1'd0)));
end

assign colMax_fu_513_p2 = ($signed(stateArray_cols_val) + $signed(16'd65535));

assign colTone_2_fu_695_p2 = (select_ln2156_fu_646_p3 + 8'd1);

assign colTone_3_fu_913_p2 = (select_ln2183_fu_840_p3 + 8'd1);

assign destColValid_fu_1044_p2 = (($signed(move_q1) > $signed(16'd65534)) ? 1'b1 : 1'b0);

assign destRowValid_fu_1004_p2 = (($signed(row_1_reg_1371) > $signed(16'd65534)) ? 1'b1 : 1'b0);

assign empty_179_fu_674_p2 = (p_cast_fu_670_p1 + 10'd32);

assign empty_180_fu_868_p2 = (p_cast7_fu_864_p1 + 10'd32);

assign empty_181_fu_878_p2 = (tmp3_cast_fu_874_p1 + add_ln2114_1_reg_1146);

assign empty_fu_322_p1 = stateArray_cols_val[9:0];

assign grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start = grp_execute_Pipeline_VITIS_LOOP_106_16_fu_304_ap_start_reg;

assign grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start = grp_execute_Pipeline_VITIS_LOOP_106_1_fu_296_ap_start_reg;

assign grp_fu_312_p4 = {{move_q1[15:8]}};

assign icmp_ln2107_fu_330_p2 = ((trunc_ln2107_fu_326_p1 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln2114_fu_401_p2 = ((trunc_ln2114_fu_393_p1 == trunc_ln2114_2_fu_397_p1) ? 1'b1 : 1'b0);

assign icmp_ln2115_fu_427_p2 = ((trunc_ln_reg_1170 == grp_fu_312_p4) ? 1'b1 : 1'b0);

assign icmp_ln2119_1_fu_437_p2 = ((trunc_ln_reg_1170 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln2119_fu_432_p2 = ((trunc_ln2114_reg_1158 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln2126_fu_456_p2 = ((stepIdx_fu_122 < 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln2131_fu_472_p2 = ((zext_ln2126_fu_468_p1 < trunc_ln2107_reg_1132) ? 1'b1 : 1'b0);

assign icmp_ln2136_fu_565_p2 = ((tmp_553_fu_555_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln2143_fu_605_p2 = ((tmp_555_fu_595_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln2156_fu_618_p2 = ((indvar_flatten_fu_134 == mul_ln2151_reg_1257) ? 1'b1 : 1'b0);

assign icmp_ln2162_fu_641_p2 = ((colTone_fu_126 == trunc_ln2114_reg_1158) ? 1'b1 : 1'b0);

assign icmp_ln2171_fu_738_p2 = (($signed(rowMax_reg_1243) < $signed(move_q0)) ? 1'b1 : 1'b0);

assign icmp_ln2173_fu_769_p2 = (($signed(colMax_reg_1250) < $signed(move_q1)) ? 1'b1 : 1'b0);

assign icmp_ln2183_fu_812_p2 = ((indvar_flatten6_fu_146 == mul_ln2151_reg_1257) ? 1'b1 : 1'b0);

assign icmp_ln2189_fu_835_p2 = ((colTone_1_fu_138 == trunc_ln2114_reg_1158) ? 1'b1 : 1'b0);

assign icmp_ln2199_fu_956_p2 = (($signed(rowMax_reg_1243) < $signed(move_q1)) ? 1'b1 : 1'b0);

assign icmp_ln2201_fu_987_p2 = (($signed(colMax_reg_1250) < $signed(move_q0)) ? 1'b1 : 1'b0);

assign icmp_ln2206_fu_1040_p2 = (($signed(rowMax_reg_1243) < $signed(row_1_reg_1371)) ? 1'b1 : 1'b0);

assign icmp_ln2207_fu_1055_p2 = (($signed(colMax_reg_1250) < $signed(move_q1)) ? 1'b1 : 1'b0);

assign lshr_ln2115_2_fu_412_p4 = {{add_ln2115_fu_407_p2[10:1]}};

assign lshr_ln3_fu_493_p4 = {{add_ln2136_fu_487_p2[10:1]}};

assign lshr_ln4_fu_576_p4 = {{add_ln2143_fu_571_p2[10:1]}};

assign lshr_ln5_fu_1025_p4 = {{add_ln2205_fu_1020_p2[10:1]}};

assign lshr_ln_fu_378_p4 = {{add_ln2114_fu_372_p2[10:1]}};

assign mul_ln2151_fu_524_p0 = mul_ln2151_fu_524_p00;

assign mul_ln2151_fu_524_p00 = trunc_ln_reg_1170;

assign mul_ln2151_fu_524_p1 = mul_ln2151_fu_524_p10;

assign mul_ln2151_fu_524_p10 = trunc_ln2114_reg_1158;

assign mul_ln_fu_477_p4 = {{{stepIdx_fu_122}, {stepIdx_fu_122}}, {1'd0}};

assign or_ln2119_fu_442_p2 = (icmp_ln2119_fu_432_p2 | icmp_ln2119_1_fu_437_p2);

assign or_ln2214_fu_1078_p2 = (row_1_reg_1371 | move_q1);

assign p_cast4_cast_fu_908_p1 = tmp_527_fu_898_p4;

assign p_cast5_fu_690_p1 = tmp_s_fu_680_p4;

assign p_cast6_fu_893_p1 = tmp_526_fu_883_p4;

assign p_cast7_fu_864_p1 = tmp_525_fu_856_p3;

assign p_cast_fu_670_p1 = tmp_fu_662_p3;

assign p_shl_fu_346_p3 = {{trunc_ln2114_1_fu_342_p1}, {6'd0}};

assign rowMax_fu_508_p2 = ($signed(stateArray_rows_val) + $signed(16'd65535));

assign rowTone_3_fu_635_p2 = (rowTone_fu_130 + 8'd1);

assign rowTone_5_fu_829_p2 = (rowTone_1_fu_142 + 8'd1);

assign select_ln2156_1_fu_654_p3 = ((icmp_ln2162_fu_641_p2[0:0] == 1'b1) ? rowTone_3_fu_635_p2 : rowTone_fu_130);

assign select_ln2156_fu_646_p3 = ((icmp_ln2162_fu_641_p2[0:0] == 1'b1) ? 8'd0 : colTone_fu_126);

assign select_ln2183_1_fu_848_p3 = ((icmp_ln2189_fu_835_p2[0:0] == 1'b1) ? rowTone_5_fu_829_p2 : rowTone_1_fu_142);

assign select_ln2183_fu_840_p3 = ((icmp_ln2189_fu_835_p2[0:0] == 1'b1) ? 8'd0 : colTone_1_fu_138);

assign shl_ln1_fu_1009_p3 = {{select_ln2183_reg_1355}, {1'd0}};

assign stateArray_data_s_address1 = stateArray_data_s_address1_local;

assign stateArray_data_s_ce1 = stateArray_data_s_ce1_local;

assign stateArray_data_s_d1 = stateArray_data_s_d1_local;

assign stateArray_data_s_we1 = stateArray_data_s_we1_local;

assign stepIdx_2_fu_462_p2 = (stepIdx_fu_122 + 5'd1);

assign tmp3_cast_fu_874_p1 = empty_180_fu_868_p2;

assign tmp_525_fu_856_p3 = {{select_ln2183_1_fu_848_p3}, {1'd0}};

assign tmp_526_fu_883_p4 = {{empty_180_fu_868_p2[9:1]}};

assign tmp_527_fu_898_p4 = {{empty_181_fu_878_p2[10:1]}};

assign tmp_552_fu_354_p3 = {{add_ln2112_fu_336_p2}, {1'd0}};

assign tmp_553_fu_555_p4 = {{move_q0[15:9]}};

assign tmp_554_fu_724_p3 = move_q0[32'd15];

assign tmp_555_fu_595_p4 = {{move_q1[7:1]}};

assign tmp_556_fu_755_p3 = move_q1[32'd15];

assign tmp_557_fu_942_p3 = move_q1[32'd15];

assign tmp_558_fu_973_p3 = move_q0[32'd15];

assign tmp_fu_662_p3 = {{select_ln2156_1_fu_654_p3}, {1'd0}};

assign tmp_s_fu_680_p4 = {{empty_179_fu_674_p2[9:1]}};

assign trunc_ln0_1_fu_1091_p1 = move_q1[9:0];

assign trunc_ln0_fu_786_p1 = move_q1[9:0];

assign trunc_ln2107_fu_326_p1 = move_q0[7:0];

assign trunc_ln2114_1_fu_342_p1 = add_ln2112_fu_336_p2[4:0];

assign trunc_ln2114_2_fu_397_p1 = move_q0[7:0];

assign trunc_ln2114_fu_393_p1 = move_q1[7:0];

assign trunc_ln2143_fu_591_p1 = move_q1[7:0];

assign trunc_ln2162_fu_716_p1 = move_q0[9:0];

assign trunc_ln2189_fu_934_p1 = move_q0[9:0];

assign xor_ln2170_fu_732_p2 = (tmp_554_fu_724_p3 ^ 1'd1);

assign xor_ln2171_fu_743_p2 = (icmp_ln2171_fu_738_p2 ^ 1'd1);

assign xor_ln2172_fu_763_p2 = (tmp_556_fu_755_p3 ^ 1'd1);

assign xor_ln2173_fu_774_p2 = (icmp_ln2173_fu_769_p2 ^ 1'd1);

assign xor_ln2198_fu_950_p2 = (tmp_557_fu_942_p3 ^ 1'd1);

assign xor_ln2199_fu_961_p2 = (icmp_ln2199_fu_956_p2 ^ 1'd1);

assign xor_ln2200_fu_981_p2 = (tmp_558_fu_973_p3 ^ 1'd1);

assign xor_ln2201_fu_992_p2 = (icmp_ln2201_fu_987_p2 ^ 1'd1);

assign xor_ln2206_fu_1050_p2 = (icmp_ln2206_reg_1405 ^ 1'd1);

assign xor_ln2207_fu_1060_p2 = (icmp_ln2207_fu_1055_p2 ^ 1'd1);

assign zext_ln2114_1_fu_362_p1 = tmp_552_fu_354_p3;

assign zext_ln2114_fu_388_p1 = lshr_ln_fu_378_p4;

assign zext_ln2115_fu_422_p1 = lshr_ln2115_2_fu_412_p4;

assign zext_ln2126_fu_468_p1 = stepIdx_fu_122;

assign zext_ln2136_fu_503_p1 = lshr_ln3_fu_493_p4;

assign zext_ln2143_fu_586_p1 = lshr_ln4_fu_576_p4;

assign zext_ln2162_fu_720_p1 = select_ln2156_reg_1297;

assign zext_ln2189_fu_938_p1 = select_ln2183_reg_1355;

assign zext_ln2205_1_fu_1016_p1 = shl_ln1_fu_1009_p3;

assign zext_ln2205_fu_1035_p1 = lshr_ln5_fu_1025_p4;

assign zext_ln316_2_fu_1095_p0 = grp_fu_1105_p3;

assign zext_ln316_2_fu_1095_p1 = $unsigned(zext_ln316_2_fu_1095_p0);

assign zext_ln316_fu_790_p0 = grp_fu_1099_p3;

assign zext_ln316_fu_790_p1 = $unsigned(zext_ln316_fu_790_p0);

always @ (posedge ap_clk) begin
    add_ln2114_1_reg_1146[0] <= 1'b0;
    mul_ln_reg_1210[0] <= 1'b0;
end

endmodule //atomflow_controller_execute
