set SynModuleInfo {
  {SRCNAME dataflow_in_loop_VITIS_LOOP_241_1.1_Block_newFuncRoot_proc.1 MODELNAME dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_1 RTLNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc_1}
  {SRCNAME getLocalImages_single MODELNAME getLocalImages_single RTLNAME atomflow_controller_getLocalImages_single
    SUBMODULES {
      {MODELNAME atomflow_controller_fsub_32ns_32ns_32_4_full_dsp_1 RTLNAME atomflow_controller_fsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME atomflow_controller_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sitofp_32ns_32_4_no_dsp_1 RTLNAME atomflow_controller_sitofp_32ns_32_4_no_dsp_1 BINDTYPE op TYPE sitofp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sparsemux_7_2_32_1_1 RTLNAME atomflow_controller_sparsemux_7_2_32_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME atomflow_controller_getLocalImages_single_mask_table_ROM_AUTO_1R RTLNAME atomflow_controller_getLocalImages_single_mask_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_getLocalImages_single_one_half_table_ROM_AUTO_1R RTLNAME atomflow_controller_getLocalImages_single_one_half_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Image_extract_next_Pipeline_VITIS_LOOP_95_1 MODELNAME Image_extract_next_Pipeline_VITIS_LOOP_95_1 RTLNAME atomflow_controller_Image_extract_next_Pipeline_VITIS_LOOP_95_1
    SUBMODULES {
      {MODELNAME atomflow_controller_partselect_1024ns_1536ns_32ns_1024_1_1 RTLNAME atomflow_controller_partselect_1024ns_1536ns_32ns_1024_1_1 BINDTYPE op TYPE partselect IMPL auto}
      {MODELNAME atomflow_controller_flow_control_loop_pipe_sequential_init RTLNAME atomflow_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME atomflow_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME Image_extract_next MODELNAME Image_extract_next RTLNAME atomflow_controller_Image_extract_next}
  {SRCNAME vector_sum_prod MODELNAME vector_sum_prod RTLNAME atomflow_controller_vector_sum_prod
    SUBMODULES {
      {MODELNAME atomflow_controller_fadd_32ns_32ns_32_4_full_dsp_0 RTLNAME atomflow_controller_fadd_32ns_32ns_32_4_full_dsp_0 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME matrix_sum_prod MODELNAME matrix_sum_prod RTLNAME atomflow_controller_matrix_sum_prod}
  {SRCNAME post_process MODELNAME post_process RTLNAME atomflow_controller_post_process
    SUBMODULES {
      {MODELNAME atomflow_controller_fdiv_32ns_32ns_32_9_no_dsp_0 RTLNAME atomflow_controller_fdiv_32ns_32ns_32_9_no_dsp_0 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dataflow_in_loop_VITIS_LOOP_241_1.1_Block_newFuncRoot_proc MODELNAME dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc RTLNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_Block_newFuncRoot_proc}
  {SRCNAME dataflow_in_loop_VITIS_LOOP_241_1.1 MODELNAME dataflow_in_loop_VITIS_LOOP_241_1_1 RTLNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1
    SUBMODULES {
      {MODELNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_curr_localImage_RAM_AUTO_1R1W_memcore RTLNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_curr_localImage_RAM_AUTO_1R1W_memcore BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_curr_localImage_RAM_AUTO_1R1W RTLNAME atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1_curr_localImage_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_fifo_w13_d7_S RTLNAME atomflow_controller_fifo_w13_d7_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc_channel_U}
      {MODELNAME atomflow_controller_fifo_w3_d7_S RTLNAME atomflow_controller_fifo_w3_d7_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc1_channel_U}
      {MODELNAME atomflow_controller_fifo_w256_d4_S RTLNAME atomflow_controller_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME localImages_U}
      {MODELNAME atomflow_controller_fifo_w32_d6_S RTLNAME atomflow_controller_fifo_w32_d6_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME curr_imageProjs_U}
      {MODELNAME atomflow_controller_fifo_w32_d2_S RTLNAME atomflow_controller_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME projSumUsed_U}
      {MODELNAME atomflow_controller_fifo_w32_d2_S RTLNAME atomflow_controller_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_U}
    }
  }
  {SRCNAME reconstruct MODELNAME reconstruct RTLNAME atomflow_controller_reconstruct}
  {SRCNAME atomflow_controller_Pipeline_VITIS_LOOP_136_1 MODELNAME atomflow_controller_Pipeline_VITIS_LOOP_136_1 RTLNAME atomflow_controller_atomflow_controller_Pipeline_VITIS_LOOP_136_1
    SUBMODULES {
      {MODELNAME atomflow_controller_sparsemux_17_3_32_1_1 RTLNAME atomflow_controller_sparsemux_17_3_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME atomflow_controller_Pipeline_VITIS_LOOP_231_1 MODELNAME atomflow_controller_Pipeline_VITIS_LOOP_231_1 RTLNAME atomflow_controller_atomflow_controller_Pipeline_VITIS_LOOP_231_1}
  {SRCNAME emissions_to_statearray_Pipeline_VITIS_LOOP_342_1 MODELNAME emissions_to_statearray_Pipeline_VITIS_LOOP_342_1 RTLNAME atomflow_controller_emissions_to_statearray_Pipeline_VITIS_LOOP_342_1}
  {SRCNAME emissions_to_statearray_Pipeline_VITIS_LOOP_348_2 MODELNAME emissions_to_statearray_Pipeline_VITIS_LOOP_348_2 RTLNAME atomflow_controller_emissions_to_statearray_Pipeline_VITIS_LOOP_348_2}
  {SRCNAME emissions_to_statearray_Pipeline_VITIS_LOOP_20_1 MODELNAME emissions_to_statearray_Pipeline_VITIS_LOOP_20_1 RTLNAME atomflow_controller_emissions_to_statearray_Pipeline_VITIS_LOOP_20_1
    SUBMODULES {
      {MODELNAME atomflow_controller_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME atomflow_controller_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sdiv_32ns_32ns_32_36_1 RTLNAME atomflow_controller_sdiv_32ns_32ns_32_36_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_srem_32ns_32ns_10_36_1 RTLNAME atomflow_controller_srem_32ns_32ns_10_36_1 BINDTYPE op TYPE srem IMPL auto LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_mac_muladd_10s_10s_10ns_10_4_1 RTLNAME atomflow_controller_mac_muladd_10s_10s_10ns_10_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME emissions_to_statearray MODELNAME emissions_to_statearray RTLNAME atomflow_controller_emissions_to_statearray
    SUBMODULES {
      {MODELNAME atomflow_controller_mul_32s_32s_64_1_1 RTLNAME atomflow_controller_mul_32s_32s_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME atomflow_controller_Pipeline_VITIS_LOOP_231_17 MODELNAME atomflow_controller_Pipeline_VITIS_LOOP_231_17 RTLNAME atomflow_controller_atomflow_controller_Pipeline_VITIS_LOOP_231_17}
  {SRCNAME load_target_geometry_Pipeline_VITIS_LOOP_342_1 MODELNAME load_target_geometry_Pipeline_VITIS_LOOP_342_1 RTLNAME atomflow_controller_load_target_geometry_Pipeline_VITIS_LOOP_342_1}
  {SRCNAME load_target_geometry_Pipeline_VITIS_LOOP_348_2 MODELNAME load_target_geometry_Pipeline_VITIS_LOOP_348_2 RTLNAME atomflow_controller_load_target_geometry_Pipeline_VITIS_LOOP_348_2}
  {SRCNAME load_target_geometry_Pipeline_VITIS_LOOP_42_1_VITIS_LOOP_44_2 MODELNAME load_target_geometry_Pipeline_VITIS_LOOP_42_1_VITIS_LOOP_44_2 RTLNAME atomflow_controller_load_target_geometry_Pipeline_VITIS_LOOP_42_1_VITIS_LOOP_44_2
    SUBMODULES {
      {MODELNAME atomflow_controller_mul_32s_31ns_62_1_1 RTLNAME atomflow_controller_mul_32s_31ns_62_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME load_target_geometry MODELNAME load_target_geometry RTLNAME atomflow_controller_load_target_geometry
    SUBMODULES {
      {MODELNAME atomflow_controller_mul_31ns_31ns_62_1_1 RTLNAME atomflow_controller_mul_31ns_31ns_62_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME findUnusableAtoms_Pipeline_VITIS_LOOP_1436_1 MODELNAME findUnusableAtoms_Pipeline_VITIS_LOOP_1436_1 RTLNAME atomflow_controller_findUnusableAtoms_Pipeline_VITIS_LOOP_1436_1}
  {SRCNAME findUnusableAtoms_Pipeline_VITIS_LOOP_1453_3 MODELNAME findUnusableAtoms_Pipeline_VITIS_LOOP_1453_3 RTLNAME atomflow_controller_findUnusableAtoms_Pipeline_VITIS_LOOP_1453_3
    SUBMODULES {
      {MODELNAME atomflow_controller_sparsemux_17_3_16_1_1 RTLNAME atomflow_controller_sparsemux_17_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME findUnusableAtoms MODELNAME findUnusableAtoms RTLNAME atomflow_controller_findUnusableAtoms
    SUBMODULES {
      {MODELNAME atomflow_controller_am_submul_9ns_10ns_10s_10_4_1 RTLNAME atomflow_controller_am_submul_9ns_10ns_10s_10_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME clearFirstNRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_421_2 MODELNAME clearFirstNRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_421_2 RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_421_2}
  {SRCNAME clearFirstNRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_459_4 MODELNAME clearFirstNRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_459_4 RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_459_4}
  {SRCNAME execute_Pipeline_VITIS_LOOP_106_1 MODELNAME execute_Pipeline_VITIS_LOOP_106_1 RTLNAME atomflow_controller_execute_Pipeline_VITIS_LOOP_106_1}
  {SRCNAME execute_Pipeline_VITIS_LOOP_106_16 MODELNAME execute_Pipeline_VITIS_LOOP_106_16 RTLNAME atomflow_controller_execute_Pipeline_VITIS_LOOP_106_16}
  {SRCNAME execute MODELNAME execute RTLNAME atomflow_controller_execute
    SUBMODULES {
      {MODELNAME atomflow_controller_mul_8ns_8ns_16_1_1 RTLNAME atomflow_controller_mul_8ns_8ns_16_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME push_back_Pipeline_VITIS_LOOP_601_1 MODELNAME push_back_Pipeline_VITIS_LOOP_601_1 RTLNAME atomflow_controller_push_back_Pipeline_VITIS_LOOP_601_1}
  {SRCNAME push_back MODELNAME push_back RTLNAME atomflow_controller_push_back}
  {SRCNAME clearFirstNRowsOrCols<HLSMoveStream> MODELNAME clearFirstNRowsOrCols_HLSMoveStream_s RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s
    SUBMODULES {
      {MODELNAME atomflow_controller_mul_10s_2ns_10_1_1 RTLNAME atomflow_controller_mul_10s_2ns_10_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_move_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_move_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_ref_tmp_i_0_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_ref_tmp_i_0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_occupiedIndices_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_occupiedIndices_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_start_colSelection_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_start_colSelection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_start_rowSelection_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_start_rowSelection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_end_rowSelection_RAM_AUTO_1R1W RTLNAME atomflow_controller_clearFirstNRowsOrCols_HLSMoveStream_s_end_rowSelection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_525_1 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_525_1 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_525_1}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_533_2 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_533_2 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_533_2}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_549_3 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_549_3 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_549_3}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_609_5 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_609_5 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_609_5}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_643_6 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_643_6 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_643_6}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_666_8 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_666_8 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_666_8}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_752_13 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_752_13 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_752_13}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_772_14 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_772_14 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_772_14}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_780_15 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_780_15 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_780_15}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1085_33 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1085_33 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1085_33}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1092_34 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1092_34 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1092_34}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1099_35 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1099_35 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1099_35}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1106_36 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1106_36 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1106_36}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1114_37 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1114_37 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1114_37
    SUBMODULES {
      {MODELNAME atomflow_controller_uitodp_64ns_64_4_no_dsp_1 RTLNAME atomflow_controller_uitodp_64ns_64_4_no_dsp_1 BINDTYPE op TYPE uitodp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sitodp_32ns_64_4_no_dsp_1 RTLNAME atomflow_controller_sitodp_32ns_64_4_no_dsp_1 BINDTYPE op TYPE sitodp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1161_38 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1161_38 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1161_38}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1168_39 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1168_39 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1168_39}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1179_40 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1179_40 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1179_40}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1186_41 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1186_41 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1186_41}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1198_42 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1198_42 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1198_42}
  {SRCNAME hlsSort MODELNAME hlsSort RTLNAME atomflow_controller_hlsSort}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1213_43 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1213_43 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1213_43}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1220_44 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1220_44 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1220_44}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_260_1 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_1 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_1}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_206_1 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_206_1 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_206_1}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_260_14 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_14 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_260_14}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_206_15 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_206_15 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_206_15}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1331_49 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1331_49 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1331_49}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1339_50 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1339_50 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1339_50}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1349_51 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1349_51 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1349_51}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_1356_52 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1356_52 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1356_52}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream>_Pipeline_VITIS_LOOP_841_18 MODELNAME sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_841_18 RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_841_18}
  {SRCNAME sortRemainingRowsOrCols<HLSMoveStream> MODELNAME sortRemainingRowsOrCols_HLSMoveStream_s RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s
    SUBMODULES {
      {MODELNAME atomflow_controller_sparsemux_17_3_16_1_1_x RTLNAME atomflow_controller_sparsemux_17_3_16_1_1_x BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME atomflow_controller_ama_addmuladd_16ns_1ns_16s_16ns_16_4_1 RTLNAME atomflow_controller_ama_addmuladd_16ns_1ns_16s_16ns_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkingSpotsPerSuitableIndexXC_data_Rbkb RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkingSpotsPerSuitableIndexXC_data_Rbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkingSpotsRemainingAtCurrentIndexXCcud RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkingSpotsRemainingAtCurrentIndexXCcud BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_start_colSelection_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_start_colSelection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usableFrontBuf_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usableFrontBuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkFrontBuf_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_parkFrontBuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_tempUsableH_RAM_1P_BRAM_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_tempUsableH_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_tempParkingH_RAM_1P_BRAM_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_tempParkingH_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usedSourceIndices_data_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usedSourceIndices_data_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usedTargetIndices_data_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_usedTargetIndices_data_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_elbow2_colSelection_1_RAM_AUTO_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_elbow2_colSelection_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_unusableAtoms_data_RAM_2P_BRAM_1R1W RTLNAME atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_s_unusableAtoms_data_RAM_2P_BRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME resolveSortingDeficiencies<HLSMoveStream>_Pipeline_VITIS_LOOP_1695_7 MODELNAME resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1695_7 RTLNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1695_7}
  {SRCNAME resolveSortingDeficiencies<HLSMoveStream>_Pipeline_VITIS_LOOP_1716_8 MODELNAME resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1716_8 RTLNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1716_8}
  {SRCNAME resolveSortingDeficiencies<HLSMoveStream>_Pipeline_VITIS_LOOP_1723_9 MODELNAME resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1723_9 RTLNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_Pipeline_VITIS_LOOP_1723_9}
  {SRCNAME resolveSortingDeficiencies<HLSMoveStream> MODELNAME resolveSortingDeficiencies_HLSMoveStream_s RTLNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_s
    SUBMODULES {
      {MODELNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_s_elbow2_colSelection_RAM_AUTO_1R1W RTLNAME atomflow_controller_resolveSortingDeficiencies_HLSMoveStream_s_elbow2_colSelection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME sortArray_impl_state_accessor<HLSMoveStream> MODELNAME sortArray_impl_state_accessor_HLSMoveStream_s RTLNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s
    SUBMODULES {
      {MODELNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_usableAtoms_data_RdEe RTLNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_usableAtoms_data_RdEe BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_usableAtoms_count_eOg RTLNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_usableAtoms_count_eOg BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_targetSites_data_Rudo RTLNAME atomflow_controller_sortArray_impl_state_accessor_HLSMoveStream_s_unusableInfo_targetSites_data_Rudo BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME atomflow_controller MODELNAME atomflow_controller RTLNAME atomflow_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME atomflow_controller_emissions_local_RAM_AUTO_1R1W RTLNAME atomflow_controller_emissions_local_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_stateArray_data_s_RAM_2P_BRAM_1R1W RTLNAME atomflow_controller_stateArray_data_s_RAM_2P_BRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME atomflow_controller_gmem0_m_axi RTLNAME atomflow_controller_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_gmem5_m_axi RTLNAME atomflow_controller_gmem5_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_gmem1_m_axi RTLNAME atomflow_controller_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_gmem6_m_axi RTLNAME atomflow_controller_gmem6_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_gmem3_m_axi RTLNAME atomflow_controller_gmem3_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_gmem4_m_axi RTLNAME atomflow_controller_gmem4_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME atomflow_controller_control_s_axi RTLNAME atomflow_controller_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME atomflow_controller_regslice_both RTLNAME atomflow_controller_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
