-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1198_42 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln1197 : IN STD_LOGIC_VECTOR (15 downto 0);
    empty : IN STD_LOGIC_VECTOR (15 downto 0);
    iter_1_reload : IN STD_LOGIC_VECTOR (4 downto 0);
    unusableInfo_usableAtoms_data_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    unusableInfo_usableAtoms_data_ce1 : OUT STD_LOGIC;
    unusableInfo_usableAtoms_data_we1 : OUT STD_LOGIC;
    unusableInfo_usableAtoms_data_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    end_colSelection_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    end_colSelection_2_ce0 : OUT STD_LOGIC;
    end_colSelection_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    targetCount_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    targetCount_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of atomflow_controller_sortRemainingRowsOrCols_HLSMoveStream_Pipeline_VITIS_LOOP_1198_42 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv56_0 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1198_fu_157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal unusableInfo_usableAtoms_data_addr_reg_237 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1203_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1203_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1198_1_fu_152_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1198_fu_168_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_60 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_28_fu_162_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal targetCount_fu_64 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal targetCount_2_fu_189_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1197_cast_fu_122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1204_fu_142_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal end_colSelection_2_ce0_local : STD_LOGIC;
    signal unusableInfo_usableAtoms_data_we1_local : STD_LOGIC;
    signal sext_ln1204_fu_205_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal unusableInfo_usableAtoms_data_ce1_local : STD_LOGIC;
    signal add_ln1204_fu_147_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_173_p4 : STD_LOGIC_VECTOR (55 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_217 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component atomflow_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component atomflow_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_60 <= ap_const_lv5_0;
                elsif (((icmp_ln1198_fu_157_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_60 <= i_28_fu_162_p2;
                end if;
            end if; 
        end if;
    end process;

    targetCount_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    targetCount_fu_64 <= zext_ln1197_cast_fu_122_p1;
                elsif ((ap_const_boolean_1 = ap_condition_217)) then 
                    targetCount_fu_64 <= targetCount_2_fu_189_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1203_reg_242 <= icmp_ln1203_fu_183_p2;
                unusableInfo_usableAtoms_data_addr_reg_237 <= zext_ln1198_1_fu_152_p1(16 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1204_fu_147_p2 <= std_logic_vector(unsigned(empty) + unsigned(trunc_ln1204_fu_142_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_217_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln1198_fu_157_p2, icmp_ln1203_fu_183_p2)
    begin
                ap_condition_217 <= ((icmp_ln1203_fu_183_p2 = ap_const_lv1_1) and (icmp_ln1198_fu_157_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln1198_fu_157_p2)
    begin
        if (((icmp_ln1198_fu_157_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    end_colSelection_2_address0 <= zext_ln1198_fu_168_p1(4 - 1 downto 0);
    end_colSelection_2_ce0 <= end_colSelection_2_ce0_local;

    end_colSelection_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            end_colSelection_2_ce0_local <= ap_const_logic_1;
        else 
            end_colSelection_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    i_28_fu_162_p2 <= std_logic_vector(unsigned(i_fu_60) + unsigned(ap_const_lv5_1));
    icmp_ln1198_fu_157_p2 <= "1" when (i_fu_60 = iter_1_reload) else "0";
    icmp_ln1203_fu_183_p2 <= "1" when (tmp_5_fu_173_p4 = ap_const_lv56_0) else "0";
        sext_ln1204_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(end_colSelection_2_q0),32));

    targetCount_1_out <= trunc_ln1204_fu_142_p1;

    targetCount_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln1198_fu_157_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln1198_fu_157_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            targetCount_1_out_ap_vld <= ap_const_logic_1;
        else 
            targetCount_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    targetCount_2_fu_189_p2 <= std_logic_vector(unsigned(targetCount_fu_64) + unsigned(ap_const_lv64_1));
    tmp_5_fu_173_p4 <= targetCount_fu_64(63 downto 8);
    trunc_ln1204_fu_142_p1 <= targetCount_fu_64(16 - 1 downto 0);
    unusableInfo_usableAtoms_data_address1 <= unusableInfo_usableAtoms_data_addr_reg_237;
    unusableInfo_usableAtoms_data_ce1 <= unusableInfo_usableAtoms_data_ce1_local;

    unusableInfo_usableAtoms_data_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            unusableInfo_usableAtoms_data_ce1_local <= ap_const_logic_1;
        else 
            unusableInfo_usableAtoms_data_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    unusableInfo_usableAtoms_data_d1 <= sext_ln1204_fu_205_p1;
    unusableInfo_usableAtoms_data_we1 <= unusableInfo_usableAtoms_data_we1_local;

    unusableInfo_usableAtoms_data_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln1203_reg_242)
    begin
        if (((icmp_ln1203_reg_242 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            unusableInfo_usableAtoms_data_we1_local <= ap_const_logic_1;
        else 
            unusableInfo_usableAtoms_data_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1197_cast_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1197),64));
    zext_ln1198_1_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1204_fu_147_p2),64));
    zext_ln1198_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_60),64));
end behav;
