-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity atomflow_controller_reconstruct is
port (
    atomLocationsSize : IN STD_LOGIC_VECTOR (31 downto 0);
    projShape0 : IN STD_LOGIC_VECTOR (31 downto 0);
    projShape1 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    atomLocations : IN STD_LOGIC_VECTOR (63 downto 0);
    psfSupersample : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem5_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem5_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem5_0_WREADY : IN STD_LOGIC;
    m_axi_gmem5_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem5_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem5_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem5_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem5_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_RVALID : IN STD_LOGIC;
    m_axi_gmem5_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem5_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem5_0_RLAST : IN STD_LOGIC;
    m_axi_gmem5_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem5_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_BVALID : IN STD_LOGIC;
    m_axi_gmem5_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem5_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    imageProjs_local : IN STD_LOGIC_VECTOR (63 downto 0);
    imageProjs_0_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem6_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem6_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem6_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_WREADY : IN STD_LOGIC;
    m_axi_gmem6_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem6_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem6_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem6_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem6_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RVALID : IN STD_LOGIC;
    m_axi_gmem6_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem6_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem6_0_RLAST : IN STD_LOGIC;
    m_axi_gmem6_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem6_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_BVALID : IN STD_LOGIC;
    m_axi_gmem6_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem6_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    fullImage : IN STD_LOGIC_VECTOR (63 downto 0);
    emissions_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_0_ce0 : OUT STD_LOGIC;
    emissions_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_0_we0 : OUT STD_LOGIC;
    emissions_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_0_ce1 : OUT STD_LOGIC;
    emissions_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_0_we1 : OUT STD_LOGIC;
    emissions_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_1_ce0 : OUT STD_LOGIC;
    emissions_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_1_we0 : OUT STD_LOGIC;
    emissions_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_1_ce1 : OUT STD_LOGIC;
    emissions_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_1_we1 : OUT STD_LOGIC;
    emissions_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_2_ce0 : OUT STD_LOGIC;
    emissions_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_2_we0 : OUT STD_LOGIC;
    emissions_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_2_ce1 : OUT STD_LOGIC;
    emissions_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_2_we1 : OUT STD_LOGIC;
    emissions_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_3_ce0 : OUT STD_LOGIC;
    emissions_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_3_we0 : OUT STD_LOGIC;
    emissions_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_3_ce1 : OUT STD_LOGIC;
    emissions_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_3_we1 : OUT STD_LOGIC;
    emissions_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_4_ce0 : OUT STD_LOGIC;
    emissions_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_4_we0 : OUT STD_LOGIC;
    emissions_4_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_4_ce1 : OUT STD_LOGIC;
    emissions_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_4_we1 : OUT STD_LOGIC;
    emissions_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_5_ce0 : OUT STD_LOGIC;
    emissions_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_5_we0 : OUT STD_LOGIC;
    emissions_5_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_5_ce1 : OUT STD_LOGIC;
    emissions_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_5_we1 : OUT STD_LOGIC;
    emissions_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_6_ce0 : OUT STD_LOGIC;
    emissions_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_6_we0 : OUT STD_LOGIC;
    emissions_6_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_6_ce1 : OUT STD_LOGIC;
    emissions_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_6_we1 : OUT STD_LOGIC;
    emissions_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_7_ce0 : OUT STD_LOGIC;
    emissions_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_7_we0 : OUT STD_LOGIC;
    emissions_7_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    emissions_7_ce1 : OUT STD_LOGIC;
    emissions_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    emissions_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    emissions_7_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    psfSupersample_ap_vld : IN STD_LOGIC;
    projShape0_ap_vld : IN STD_LOGIC;
    projShape1_ap_vld : IN STD_LOGIC;
    atomLocations_ap_vld : IN STD_LOGIC;
    fullImage_ap_vld : IN STD_LOGIC;
    imageProjs_local_ap_vld : IN STD_LOGIC;
    imageProjs_0_0_val_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of atomflow_controller_reconstruct is 
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_conv : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_ce0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_we0 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_ce1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_we1 : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        conv : IN STD_LOGIC_VECTOR (15 downto 0);
        psfSupersample : IN STD_LOGIC_VECTOR (31 downto 0);
        projShape0 : IN STD_LOGIC_VECTOR (31 downto 0);
        projShape1 : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        atomLocations : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem6_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem6_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem6_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem6_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem6_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem6_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem6_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem6_0_WREADY : IN STD_LOGIC;
        m_axi_gmem6_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem6_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem6_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem6_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem6_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem6_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem6_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem6_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem6_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem6_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem6_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_RVALID : IN STD_LOGIC;
        m_axi_gmem6_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem6_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem6_0_RLAST : IN STD_LOGIC;
        m_axi_gmem6_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem6_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_BVALID : IN STD_LOGIC;
        m_axi_gmem6_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem6_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem6_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem6_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        fullImage : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem5_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem5_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem5_0_WREADY : IN STD_LOGIC;
        m_axi_gmem5_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem5_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem5_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem5_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem5_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_RVALID : IN STD_LOGIC;
        m_axi_gmem5_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem5_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem5_0_RLAST : IN STD_LOGIC;
        m_axi_gmem5_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem5_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_BVALID : IN STD_LOGIC;
        m_axi_gmem5_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem5_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        imageProjs_local : IN STD_LOGIC_VECTOR (63 downto 0);
        imageProjs_0_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_0_ce0 : OUT STD_LOGIC;
        emissions_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_0_we0 : OUT STD_LOGIC;
        emissions_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_0_ce1 : OUT STD_LOGIC;
        emissions_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_0_we1 : OUT STD_LOGIC;
        emissions_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_1_ce0 : OUT STD_LOGIC;
        emissions_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_1_we0 : OUT STD_LOGIC;
        emissions_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_1_ce1 : OUT STD_LOGIC;
        emissions_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_1_we1 : OUT STD_LOGIC;
        emissions_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_2_ce0 : OUT STD_LOGIC;
        emissions_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_2_we0 : OUT STD_LOGIC;
        emissions_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_2_ce1 : OUT STD_LOGIC;
        emissions_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_2_we1 : OUT STD_LOGIC;
        emissions_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_3_ce0 : OUT STD_LOGIC;
        emissions_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_3_we0 : OUT STD_LOGIC;
        emissions_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_3_ce1 : OUT STD_LOGIC;
        emissions_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_3_we1 : OUT STD_LOGIC;
        emissions_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_4_ce0 : OUT STD_LOGIC;
        emissions_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_4_we0 : OUT STD_LOGIC;
        emissions_4_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_4_ce1 : OUT STD_LOGIC;
        emissions_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_4_we1 : OUT STD_LOGIC;
        emissions_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_5_ce0 : OUT STD_LOGIC;
        emissions_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_5_we0 : OUT STD_LOGIC;
        emissions_5_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_5_ce1 : OUT STD_LOGIC;
        emissions_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_5_we1 : OUT STD_LOGIC;
        emissions_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_6_ce0 : OUT STD_LOGIC;
        emissions_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_6_we0 : OUT STD_LOGIC;
        emissions_6_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_6_ce1 : OUT STD_LOGIC;
        emissions_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_6_we1 : OUT STD_LOGIC;
        emissions_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_7_ce0 : OUT STD_LOGIC;
        emissions_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_7_we0 : OUT STD_LOGIC;
        emissions_7_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        emissions_7_ce1 : OUT STD_LOGIC;
        emissions_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        emissions_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        emissions_7_we1 : OUT STD_LOGIC;
        conv_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        psfSupersample_ap_vld : IN STD_LOGIC;
        projShape0_ap_vld : IN STD_LOGIC;
        projShape1_ap_vld : IN STD_LOGIC;
        atomLocations_ap_vld : IN STD_LOGIC;
        fullImage_ap_vld : IN STD_LOGIC;
        imageProjs_local_ap_vld : IN STD_LOGIC;
        imageProjs_0_0_val_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_VITIS_LOOP_241_1_1_U0 : component atomflow_controller_dataflow_in_loop_VITIS_LOOP_241_1_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        conv => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_conv,
        psfSupersample => psfSupersample,
        projShape0 => projShape0,
        projShape1 => projShape1,
        m_axi_gmem0_0_AWVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_0_AWADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => ap_const_logic_0,
        m_axi_gmem0_0_WDATA => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST => m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID => m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM => m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER => m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP => m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID => ap_const_logic_0,
        m_axi_gmem0_0_BREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BID => ap_const_lv1_0,
        m_axi_gmem0_0_BUSER => ap_const_lv1_0,
        atomLocations => atomLocations,
        m_axi_gmem6_0_AWVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWVALID,
        m_axi_gmem6_0_AWREADY => ap_const_logic_0,
        m_axi_gmem6_0_AWADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWADDR,
        m_axi_gmem6_0_AWID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWID,
        m_axi_gmem6_0_AWLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWLEN,
        m_axi_gmem6_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWSIZE,
        m_axi_gmem6_0_AWBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWBURST,
        m_axi_gmem6_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWLOCK,
        m_axi_gmem6_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWCACHE,
        m_axi_gmem6_0_AWPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWPROT,
        m_axi_gmem6_0_AWQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWQOS,
        m_axi_gmem6_0_AWREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWREGION,
        m_axi_gmem6_0_AWUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_AWUSER,
        m_axi_gmem6_0_WVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WVALID,
        m_axi_gmem6_0_WREADY => ap_const_logic_0,
        m_axi_gmem6_0_WDATA => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WDATA,
        m_axi_gmem6_0_WSTRB => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WSTRB,
        m_axi_gmem6_0_WLAST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WLAST,
        m_axi_gmem6_0_WID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WID,
        m_axi_gmem6_0_WUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_WUSER,
        m_axi_gmem6_0_ARVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARVALID,
        m_axi_gmem6_0_ARREADY => m_axi_gmem6_0_ARREADY,
        m_axi_gmem6_0_ARADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARADDR,
        m_axi_gmem6_0_ARID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARID,
        m_axi_gmem6_0_ARLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLEN,
        m_axi_gmem6_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARSIZE,
        m_axi_gmem6_0_ARBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARBURST,
        m_axi_gmem6_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLOCK,
        m_axi_gmem6_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARCACHE,
        m_axi_gmem6_0_ARPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARPROT,
        m_axi_gmem6_0_ARQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARQOS,
        m_axi_gmem6_0_ARREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARREGION,
        m_axi_gmem6_0_ARUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARUSER,
        m_axi_gmem6_0_RVALID => m_axi_gmem6_0_RVALID,
        m_axi_gmem6_0_RREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_RREADY,
        m_axi_gmem6_0_RDATA => m_axi_gmem6_0_RDATA,
        m_axi_gmem6_0_RLAST => m_axi_gmem6_0_RLAST,
        m_axi_gmem6_0_RID => m_axi_gmem6_0_RID,
        m_axi_gmem6_0_RFIFONUM => m_axi_gmem6_0_RFIFONUM,
        m_axi_gmem6_0_RUSER => m_axi_gmem6_0_RUSER,
        m_axi_gmem6_0_RRESP => m_axi_gmem6_0_RRESP,
        m_axi_gmem6_0_BVALID => ap_const_logic_0,
        m_axi_gmem6_0_BREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_BREADY,
        m_axi_gmem6_0_BRESP => ap_const_lv2_0,
        m_axi_gmem6_0_BID => ap_const_lv1_0,
        m_axi_gmem6_0_BUSER => ap_const_lv1_0,
        fullImage => fullImage,
        m_axi_gmem5_0_AWVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWVALID,
        m_axi_gmem5_0_AWREADY => ap_const_logic_0,
        m_axi_gmem5_0_AWADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWADDR,
        m_axi_gmem5_0_AWID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWID,
        m_axi_gmem5_0_AWLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWLEN,
        m_axi_gmem5_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWSIZE,
        m_axi_gmem5_0_AWBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWBURST,
        m_axi_gmem5_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWLOCK,
        m_axi_gmem5_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWCACHE,
        m_axi_gmem5_0_AWPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWPROT,
        m_axi_gmem5_0_AWQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWQOS,
        m_axi_gmem5_0_AWREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWREGION,
        m_axi_gmem5_0_AWUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_AWUSER,
        m_axi_gmem5_0_WVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WVALID,
        m_axi_gmem5_0_WREADY => ap_const_logic_0,
        m_axi_gmem5_0_WDATA => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WDATA,
        m_axi_gmem5_0_WSTRB => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WSTRB,
        m_axi_gmem5_0_WLAST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WLAST,
        m_axi_gmem5_0_WID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WID,
        m_axi_gmem5_0_WUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_WUSER,
        m_axi_gmem5_0_ARVALID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARVALID,
        m_axi_gmem5_0_ARREADY => m_axi_gmem5_0_ARREADY,
        m_axi_gmem5_0_ARADDR => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARADDR,
        m_axi_gmem5_0_ARID => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARID,
        m_axi_gmem5_0_ARLEN => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLEN,
        m_axi_gmem5_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARSIZE,
        m_axi_gmem5_0_ARBURST => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARBURST,
        m_axi_gmem5_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLOCK,
        m_axi_gmem5_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARCACHE,
        m_axi_gmem5_0_ARPROT => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARPROT,
        m_axi_gmem5_0_ARQOS => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARQOS,
        m_axi_gmem5_0_ARREGION => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARREGION,
        m_axi_gmem5_0_ARUSER => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARUSER,
        m_axi_gmem5_0_RVALID => m_axi_gmem5_0_RVALID,
        m_axi_gmem5_0_RREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_RREADY,
        m_axi_gmem5_0_RDATA => m_axi_gmem5_0_RDATA,
        m_axi_gmem5_0_RLAST => m_axi_gmem5_0_RLAST,
        m_axi_gmem5_0_RID => m_axi_gmem5_0_RID,
        m_axi_gmem5_0_RFIFONUM => m_axi_gmem5_0_RFIFONUM,
        m_axi_gmem5_0_RUSER => m_axi_gmem5_0_RUSER,
        m_axi_gmem5_0_RRESP => m_axi_gmem5_0_RRESP,
        m_axi_gmem5_0_BVALID => ap_const_logic_0,
        m_axi_gmem5_0_BREADY => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_BREADY,
        m_axi_gmem5_0_BRESP => ap_const_lv2_0,
        m_axi_gmem5_0_BID => ap_const_lv1_0,
        m_axi_gmem5_0_BUSER => ap_const_lv1_0,
        imageProjs_local => imageProjs_local,
        imageProjs_0_0_val => imageProjs_0_0_val,
        emissions_0_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_address0,
        emissions_0_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_ce0,
        emissions_0_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_d0,
        emissions_0_q0 => ap_const_lv32_0,
        emissions_0_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_we0,
        emissions_0_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_address1,
        emissions_0_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_ce1,
        emissions_0_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_d1,
        emissions_0_q1 => ap_const_lv32_0,
        emissions_0_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_we1,
        emissions_1_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_address0,
        emissions_1_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_ce0,
        emissions_1_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_d0,
        emissions_1_q0 => ap_const_lv32_0,
        emissions_1_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_we0,
        emissions_1_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_address1,
        emissions_1_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_ce1,
        emissions_1_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_d1,
        emissions_1_q1 => ap_const_lv32_0,
        emissions_1_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_we1,
        emissions_2_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_address0,
        emissions_2_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_ce0,
        emissions_2_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_d0,
        emissions_2_q0 => ap_const_lv32_0,
        emissions_2_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_we0,
        emissions_2_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_address1,
        emissions_2_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_ce1,
        emissions_2_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_d1,
        emissions_2_q1 => ap_const_lv32_0,
        emissions_2_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_we1,
        emissions_3_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_address0,
        emissions_3_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_ce0,
        emissions_3_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_d0,
        emissions_3_q0 => ap_const_lv32_0,
        emissions_3_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_we0,
        emissions_3_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_address1,
        emissions_3_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_ce1,
        emissions_3_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_d1,
        emissions_3_q1 => ap_const_lv32_0,
        emissions_3_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_we1,
        emissions_4_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_address0,
        emissions_4_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_ce0,
        emissions_4_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_d0,
        emissions_4_q0 => ap_const_lv32_0,
        emissions_4_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_we0,
        emissions_4_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_address1,
        emissions_4_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_ce1,
        emissions_4_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_d1,
        emissions_4_q1 => ap_const_lv32_0,
        emissions_4_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_we1,
        emissions_5_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_address0,
        emissions_5_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_ce0,
        emissions_5_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_d0,
        emissions_5_q0 => ap_const_lv32_0,
        emissions_5_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_we0,
        emissions_5_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_address1,
        emissions_5_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_ce1,
        emissions_5_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_d1,
        emissions_5_q1 => ap_const_lv32_0,
        emissions_5_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_we1,
        emissions_6_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_address0,
        emissions_6_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_ce0,
        emissions_6_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_d0,
        emissions_6_q0 => ap_const_lv32_0,
        emissions_6_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_we0,
        emissions_6_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_address1,
        emissions_6_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_ce1,
        emissions_6_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_d1,
        emissions_6_q1 => ap_const_lv32_0,
        emissions_6_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_we1,
        emissions_7_address0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_address0,
        emissions_7_ce0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_ce0,
        emissions_7_d0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_d0,
        emissions_7_q0 => ap_const_lv32_0,
        emissions_7_we0 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_we0,
        emissions_7_address1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_address1,
        emissions_7_ce1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_ce1,
        emissions_7_d1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_d1,
        emissions_7_q1 => ap_const_lv32_0,
        emissions_7_we1 => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_we1,
        conv_ap_vld => ap_const_logic_0,
        ap_start => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_start,
        psfSupersample_ap_vld => psfSupersample_ap_vld,
        projShape0_ap_vld => projShape0_ap_vld,
        projShape1_ap_vld => projShape1_ap_vld,
        atomLocations_ap_vld => atomLocations_ap_vld,
        fullImage_ap_vld => fullImage_ap_vld,
        imageProjs_local_ap_vld => imageProjs_local_ap_vld,
        imageProjs_0_0_val_ap_vld => imageProjs_0_0_val_ap_vld,
        ap_done => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done,
        ap_ready => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready,
        ap_idle => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_idle,
        ap_continue => dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv32_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv32_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv32_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv32_1));
                elsif (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((loop_dataflow_output_count = ap_const_lv32_0) and (ap_start = ap_const_logic_0) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_idle = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_minus_1 <= std_logic_vector(unsigned(atomLocationsSize) - unsigned(ap_const_lv32_1));

    dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_VITIS_LOOP_241_1_1_U0_ap_start <= ap_start;
    dataflow_in_loop_VITIS_LOOP_241_1_1_U0_conv <= loop_dataflow_input_count(16 - 1 downto 0);
    emissions_0_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_address0;
    emissions_0_address1 <= ap_const_lv8_0;
    emissions_0_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_ce0;
    emissions_0_ce1 <= ap_const_logic_0;
    emissions_0_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_d0;
    emissions_0_d1 <= ap_const_lv32_0;
    emissions_0_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_0_we0;
    emissions_0_we1 <= ap_const_logic_0;
    emissions_1_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_address0;
    emissions_1_address1 <= ap_const_lv8_0;
    emissions_1_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_ce0;
    emissions_1_ce1 <= ap_const_logic_0;
    emissions_1_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_d0;
    emissions_1_d1 <= ap_const_lv32_0;
    emissions_1_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_1_we0;
    emissions_1_we1 <= ap_const_logic_0;
    emissions_2_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_address0;
    emissions_2_address1 <= ap_const_lv8_0;
    emissions_2_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_ce0;
    emissions_2_ce1 <= ap_const_logic_0;
    emissions_2_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_d0;
    emissions_2_d1 <= ap_const_lv32_0;
    emissions_2_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_2_we0;
    emissions_2_we1 <= ap_const_logic_0;
    emissions_3_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_address0;
    emissions_3_address1 <= ap_const_lv8_0;
    emissions_3_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_ce0;
    emissions_3_ce1 <= ap_const_logic_0;
    emissions_3_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_d0;
    emissions_3_d1 <= ap_const_lv32_0;
    emissions_3_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_3_we0;
    emissions_3_we1 <= ap_const_logic_0;
    emissions_4_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_address0;
    emissions_4_address1 <= ap_const_lv8_0;
    emissions_4_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_ce0;
    emissions_4_ce1 <= ap_const_logic_0;
    emissions_4_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_d0;
    emissions_4_d1 <= ap_const_lv32_0;
    emissions_4_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_4_we0;
    emissions_4_we1 <= ap_const_logic_0;
    emissions_5_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_address0;
    emissions_5_address1 <= ap_const_lv8_0;
    emissions_5_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_ce0;
    emissions_5_ce1 <= ap_const_logic_0;
    emissions_5_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_d0;
    emissions_5_d1 <= ap_const_lv32_0;
    emissions_5_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_5_we0;
    emissions_5_we1 <= ap_const_logic_0;
    emissions_6_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_address0;
    emissions_6_address1 <= ap_const_lv8_0;
    emissions_6_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_ce0;
    emissions_6_ce1 <= ap_const_logic_0;
    emissions_6_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_d0;
    emissions_6_d1 <= ap_const_lv32_0;
    emissions_6_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_6_we0;
    emissions_6_we1 <= ap_const_logic_0;
    emissions_7_address0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_address0;
    emissions_7_address1 <= ap_const_lv8_0;
    emissions_7_ce0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_ce0;
    emissions_7_ce1 <= ap_const_logic_0;
    emissions_7_d0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_d0;
    emissions_7_d1 <= ap_const_lv32_0;
    emissions_7_we0 <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_emissions_7_we0;
    emissions_7_we1 <= ap_const_logic_0;
    m_axi_gmem0_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARADDR;
    m_axi_gmem0_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARBURST;
    m_axi_gmem0_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARCACHE;
    m_axi_gmem0_0_ARID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARID;
    m_axi_gmem0_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLEN;
    m_axi_gmem0_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARLOCK;
    m_axi_gmem0_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARPROT;
    m_axi_gmem0_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARQOS;
    m_axi_gmem0_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARREGION;
    m_axi_gmem0_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARSIZE;
    m_axi_gmem0_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARUSER;
    m_axi_gmem0_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_ARVALID;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_0_RREADY <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem0_0_RREADY;
    m_axi_gmem0_0_WDATA <= ap_const_lv64_0;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv8_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    m_axi_gmem5_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARADDR;
    m_axi_gmem5_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARBURST;
    m_axi_gmem5_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARCACHE;
    m_axi_gmem5_0_ARID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARID;
    m_axi_gmem5_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLEN;
    m_axi_gmem5_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARLOCK;
    m_axi_gmem5_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARPROT;
    m_axi_gmem5_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARQOS;
    m_axi_gmem5_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARREGION;
    m_axi_gmem5_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARSIZE;
    m_axi_gmem5_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARUSER;
    m_axi_gmem5_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_ARVALID;
    m_axi_gmem5_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem5_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem5_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem5_0_AWID <= ap_const_lv1_0;
    m_axi_gmem5_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem5_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem5_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem5_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem5_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem5_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem5_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem5_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem5_0_BREADY <= ap_const_logic_0;
    m_axi_gmem5_0_RREADY <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem5_0_RREADY;
    m_axi_gmem5_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem5_0_WID <= ap_const_lv1_0;
    m_axi_gmem5_0_WLAST <= ap_const_logic_0;
    m_axi_gmem5_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem5_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem5_0_WVALID <= ap_const_logic_0;
    m_axi_gmem6_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARADDR;
    m_axi_gmem6_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARBURST;
    m_axi_gmem6_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARCACHE;
    m_axi_gmem6_0_ARID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARID;
    m_axi_gmem6_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLEN;
    m_axi_gmem6_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARLOCK;
    m_axi_gmem6_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARPROT;
    m_axi_gmem6_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARQOS;
    m_axi_gmem6_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARREGION;
    m_axi_gmem6_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARSIZE;
    m_axi_gmem6_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARUSER;
    m_axi_gmem6_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_ARVALID;
    m_axi_gmem6_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem6_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem6_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem6_0_AWID <= ap_const_lv1_0;
    m_axi_gmem6_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem6_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem6_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem6_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem6_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem6_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem6_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem6_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem6_0_BREADY <= ap_const_logic_0;
    m_axi_gmem6_0_RREADY <= dataflow_in_loop_VITIS_LOOP_241_1_1_U0_m_axi_gmem6_0_RREADY;
    m_axi_gmem6_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem6_0_WID <= ap_const_lv1_0;
    m_axi_gmem6_0_WLAST <= ap_const_logic_0;
    m_axi_gmem6_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem6_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem6_0_WVALID <= ap_const_logic_0;
end behav;
